### ISSUE TITLE
Raise correct error on single semicolon

### ISSUE THREAD

**Issue by ai** [postcss/postcss#1004]
Input:

```
:
```

Current error:

```
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 TypeError: Cannot read property '0' of undefined
     at Parser.decl (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:203:25)
     at Parser.other (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:170:18)
     at Parser.loop (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:81:26)
     at parse (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parse.js:26:16)
     at new LazyResult (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/lazy-result.js:70:24)
     at Processor.process (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/processor.js:117:12)
     at getCode.then.e (/home/svipben/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/stylelint/lib/getPostcssResult.js:83:29)
```

Expected error: `CssSyntaxError`.

Origin issue: https://github.com/postcss/postcss-scss/issues/57 and https://github.com/shinnn/vscode-stylelint/issues/65#issuecomment-292880983

/cc @svipben @shinnn

**Comment by ai** [comment]
Done 4adaf97

But fix will be released only in next 6.0.

**Comment by shinnn** [comment]
Great work, @ai.

**Comment by equinusocio** [comment]
I get the same error with postcss 6.0

**Comment by ai** [comment]
@equinusocio give me more information. Stacktrace, input CSS

**Comment by equinusocio** [comment]
I'm using `gulp-postcss` with `postcss-cssnext`. I'm using `.postcss` file extension and every time i write a selector that start with `:` i get this error:

> TypeError: Cannot read property '0' of undefined at Parser.decl (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:203:25) at Parser.other (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:170:18) at Parser.loop (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss/lib/parser.js:81:26) at parse (/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/

**Comment by ai** [comment]
Can you check PostCSS version in `/Users/equinusocio/.vscode/extensions/shinnn.stylelint-0.24.0/node_modules/postcss`?

**Comment by equinusocio** [comment]
`"version": "5.2.16"`.

So `shinnn.stylelint` is using an old `postcss` version?

**Comment by shinnn** [comment]
`shinnn.stylelint` is not `gulp-postcss`.

**Comment by equinusocio** [comment]
@shinnn Yes i know, but I didn't know what was the caused

**Comment by shinnn** [comment]
vscode-stylelint is just a wrapper for [stylelint](https://github.com/stylelint/stylelint), which still uses PostCSS 5.x. Wait for https://github.com/stylelint/stylelint/pull/2561 being merged.

**Comment by equinusocio** [comment]
Ok thank you.
