### ISSUE TITLE
Error on Build - Gulp

### ISSUE THREAD

**Issue by nickmistretta9** [postcss/postcss#1050]
I have recently come into an error using gulp-postcss. I am getting errors trying to run my build task which has been causing quite a headache. The task at hand is 
```
gulp.task('css', function() { 
    var plugins = [
		autoprefixer({browsers:['last 2 versions']}),
		cssnano()
	];
	return gulp.src('dev/css/*.css')
	.pipe(postcss(plugins))
	.pipe(gulp.dest('dist/css'));
});
```
The task works if I comment out the call to cssnano and only leave autoprefixer, but if I don't, it gives me this error: 
```
events.js:182
      throw er; // Unhandled 'error' event
      ^
RangeError: Maximum call stack size exceeded
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:20:28)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
    at recurse (/Applications/MAMP/htdocs/gulp-test/node_modules/postcss-merge-idents/dist/index.js:22:20)
```
I have tried everything I could find to try and get it to work and still nothing has. I have also noticed that this issue is occurring only on recent projects, as I hadn't previously had any issues. I would really appreciate any advice on what to do in order to fix the error.

**Comment by ai** [comment]
Sorry, you need to open issue in `postcss-merge-idents`,seems like we have a issue there.

I like to help, but I don’t know this project. It will be faster to just open issue there.
