### ISSUE TITLE
EISDIR: illegal operation on a directory ...

### ISSUE THREAD

**Issue by nextgenthemes** [postcss/postcss#1054]
I am trying to build bootstrap 4.0 and get this error.

**{ Error: EISDIR: illegal operation on a directory, read
    at Error (native) errno: -21, code: 'EISDIR', syscall: 'read' }**

System: Ubuntu 17.04

Installed node the offical way.

Installed ruby and bundler like with rbenv as [described here.](https://gorails.com/setup/ubuntu/17.04) I had the build failing on ubuntu 16.10 as well then upgraded to 17.04 and also had outdated ruby installed with apt but purged that and tried various other ways to reinstall ruby and bunder but no luck.

**I am willing to pay someone who helps me get this mess solved.** 

```
in ~/wp-content/themes/bootstrap on git:v4-dev x [21:48:46] 
$ npm run css                   

> bootstrap@4.0.0-alpha.6 css /home/user23/wp-content/themes/bootstrap
> npm-run-all css-lint css-compile css-prefix css-minify


> bootstrap@4.0.0-alpha.6 css-lint /home/user23/wp-content/themes/bootstrap
> bundle exec scss-lint --config .scss-lint.yml scss/*.scss


> bootstrap@4.0.0-alpha.6 css-compile /home/user23/wp-content/themes/bootstrap
> node-sass --output-style expanded --source-map true --precision 6 scss/bootstrap.scss dist/css/bootstrap.css && node-sass --output-style expanded --source-map true --precision 6 scss/bootstrap-grid.scss dist/css/bootstrap-grid.css && node-sass --output-style expanded --source-map true --precision 6 scss/bootstrap-reboot.scss dist/css/bootstrap-reboot.css

Rendering Complete, saving .css file...
Wrote CSS to /home/user23/wp-content/themes/bootstrap/dist/css/bootstrap.css
Wrote Source Map to /home/user23/wp-content/themes/bootstrap/dist/css/bootstrap.css.map
Rendering Complete, saving .css file...
Wrote CSS to /home/user23/wp-content/themes/bootstrap/dist/css/bootstrap-grid.css
Wrote Source Map to /home/user23/wp-content/themes/bootstrap/dist/css/bootstrap-grid.css.map
Rendering Complete, saving .css file...
Wrote CSS to /home/user23/wp-content/themes/bootstrap/dist/css/bootstrap-reboot.css
Wrote Source Map to /home/user23/wp-content/themes/bootstrap/dist/css/bootstrap-reboot.css.map

> bootstrap@4.0.0-alpha.6 css-prefix /home/user23/wp-content/themes/bootstrap
> postcss --config build/ --replace dist/css/*.css

✖ Processing dist/css/bootstrap.min.css
{ Error: EISDIR: illegal operation on a directory, read
    at Error (native) errno: -21, code: 'EISDIR', syscall: 'read' }

npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "css-prefix"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! bootstrap@4.0.0-alpha.6 css-prefix: `postcss --config build/ --replace dist/css/*.css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap@4.0.0-alpha.6 css-prefix script 'postcss --config build/ --replace dist/css/*.css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     postcss --config build/ --replace dist/css/*.css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bootstrap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bootstrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user23/wp-content/themes/bootstrap/npm-debug.log
ERROR: "css-prefix" exited with 1.

npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "css"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! bootstrap@4.0.0-alpha.6 css: `npm-run-all css-lint css-compile css-prefix css-minify`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bootstrap@4.0.0-alpha.6 css script 'npm-run-all css-lint css-compile css-prefix css-minify'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bootstrap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all css-lint css-compile css-prefix css-minify
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bootstrap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bootstrap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user23/wp-content/themes/bootstrap/npm-debug.log
```

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'css' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 verbose run-script [ 'precss', 'css', 'postcss' ]
5 info lifecycle bootstrap@4.0.0-alpha.6~precss: bootstrap@4.0.0-alpha.6
6 silly lifecycle bootstrap@4.0.0-alpha.6~precss: no script for precss, continuing
7 info lifecycle bootstrap@4.0.0-alpha.6~css: bootstrap@4.0.0-alpha.6
8 verbose lifecycle bootstrap@4.0.0-alpha.6~css: unsafe-perm in lifecycle true
9 verbose lifecycle bootstrap@4.0.0-alpha.6~css: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/user23/wp-content/themes/bootstrap/node_modules/.bin:/home/user23/.rbenv/plugins/ruby-build/bin:/home/user23/.rbenv/shims:/home/user23/.rbenv/bin:/home/user23/.npm-packages/bin:/home/user23/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/user23/bin/:/home/user23/bin/.old:/home/user23/bin/automation-wp:/home/user23/bin/server-setup:/home/user23/bin/sabnzb:/home/user23/bin/install:/home/user23/.composer/vendor/bin
10 verbose lifecycle bootstrap@4.0.0-alpha.6~css: CWD: /home/user23/wp-content/themes/bootstrap
11 silly lifecycle bootstrap@4.0.0-alpha.6~css: Args: [ '-c',
11 silly lifecycle   'npm-run-all css-lint css-compile css-prefix css-minify' ]
12 silly lifecycle bootstrap@4.0.0-alpha.6~css: Returned: code: 1  signal: null
13 info lifecycle bootstrap@4.0.0-alpha.6~css: Failed to exec css script
14 verbose stack Error: bootstrap@4.0.0-alpha.6 css: `npm-run-all css-lint css-compile css-prefix css-minify`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid bootstrap@4.0.0-alpha.6
16 verbose cwd /home/user23/wp-content/themes/bootstrap
17 error Linux 4.10.0-28-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "css"
19 error node v6.11.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error bootstrap@4.0.0-alpha.6 css: `npm-run-all css-lint css-compile css-prefix css-minify`
22 error Exit status 1
23 error Failed at the bootstrap@4.0.0-alpha.6 css script 'npm-run-all css-lint css-compile css-prefix css-minify'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the bootstrap package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm-run-all css-lint css-compile css-prefix css-minify
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs bootstrap
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls bootstrap
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

[EISDIR error seem to occurs when you try to open a file](https://stackoverflow.com/questions/25883775/node-js-readfilesync-function)

**Comment by ai** [comment]
Hi. Please open issue in postcss-cli. This repo is for core module, which only works with CSS and don't read files.

I am happy to help you, but postcss-cli is separated project with own team.
