### ISSUE TITLE
Keep getting error

### ISSUE THREAD

**Issue by SilentImp** [postcss/postcss#1067]
[package-lock.json, postcss.config.js in the attachment. configs.zip](https://github.com/postcss/postcss/files/1287584/configs.zip)

I have tried both "precss": "^2.0.0", and "precss": "^1.4.0", — result the same:
```
Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.11, but postcss-advanced-variables uses 5.2.17. Perhaps this is the source of the error below.
```
and bellow:
```
ERROR in ../~/css-loader?{"importLoaders":1}!../~/postcss-loader/lib?{"modules":true,"sourceMap":true,"plugins":[{"version":"6.0.11","plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"postcssPlugin":"precss","postcssVersion":"6.0.11"},null,null,null]}!./components/Header/header.pcss
Module build failed: TypeError: Cannot read property 'replace' of undefined
    at getVariableTransformedString (/Users/silentimp/Work/Project/node_modules/postcss-advanced-variables/index.js:47:16)
    at eachAtIfRule (/Users/silentimp/Work/Project/node_modules/postcss-advanced-variables/index.js:192:18)
    at eachAtRule (/Users/silentimp/Work/Project/node_modules/postcss-advanced-variables/index.js:103:40)
    at each (/Users/silentimp/Work/Project/node_modules/postcss-advanced-variables/index.js:65:45)
    at each (/Users/silentimp/Work/Project/node_modules/postcss-advanced-variables/index.js:67:20)
    at each (/Users/silentimp/Work/Project/node_modules/postcss-advanced-variables/index.js:67:20)
    at each (/Users/silentimp/Work/Project/node_modules/postcss-advanced-variables/index.js:67:20)
    at each (/Users/silentimp/Work/Project/node_modules/postcss-advanced-variables/index.js:67:20)
    at each (/Users/silentimp/Work/Project/node_modules/postcss-advanced-variables/index.js:67:20)
    at /Users/silentimp/Work/Project/node_modules/postcss-advanced-variables/index.js:246:3
    at LazyResult.run (/Users/silentimp/Work/Project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:270:20)
    at LazyResult.asyncTick (/Users/silentimp/Work/Project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:185:32)
    at LazyResult.asyncTick (/Users/silentimp/Work/Project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:197:22)
    at /Users/silentimp/Work/Project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:190:27
    at <anonymous>
 @ ./components/Header/header.pcss 4:14-152 18:2-22:4 19:20-158
 @ ./components/Header/index.jsx
 @ ./pages/Home/index.jsx
 @ ./app.jsx
 @ multi babel-polyfill react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./app.jsx
```

**Comment by deflock** [comment]
Looks like advanced-variables' issue/feature. Are you trying to use @if statements with single operand?

**Comment by ai** [comment]
Did you tried to downgrade PostCSS to 5.x? You can check it by `npm ls`.

Seems like problem is that PreCSS was not updated to 6.0 API.

**Comment by zengjinchaodean** [comment]
I also encountered the same problem, my view version after version is 6.0.11, but when I use the nested style will also appear in 'Your current PostCSS version is 6.0.11, but postcss-advanced-variables uses 5.2.17. Perhaps this is the source of the error below. "

**Comment by ai** [comment]
@zengjinchaodean did you try `npm ls`? Did you find PostCSS 5 in `npm ls`?

**Comment by zengjinchaodean** [comment]
I've tried, and only postcss6

**Comment by zengjinchaodean** [comment]
i check again , Below gulp-postcss, there is the 5.2.17 version of postcss, with the postcss6.0.11 version at the same level as gulp-postcss

**Comment by ai** [comment]
@zengjinchaodean show me your error and `npm ls` output

**Comment by ai** [comment]
> Below gulp-postcss, there is the 5.2.17 version of postcss

This is source of problem. `gulp-postcss` uses PostCSS 5. Update `gulp-postcss`

**Comment by zengjinchaodean** [comment]
The problem is settled, thank you

**Comment by godfan123** [comment]
gg
