### ISSUE TITLE
JS API Documentation isn't working.

### ISSUE THREAD

**Issue by coldtelling** [postcss/postcss#1148]
```
npm init -y
npm i -D postcss precss autoprefixer fs
mkdir src dest
echo $null >> app.js
```

```
const fs = require('fs');
const postcss = require('postcss');
const precss = require('precss');
const autoprefixer = require('autoprefixer');

fs.readFile('src/app.css', (err, css) => {
    postcss([precss, autoprefixer])
        .process(css, { from: 'src/app.css', to: 'dest/app.css' })
        .then(result => {
            fs.writeFile('dest/app.css', result.css);
            if ( result.map ) fs.writeFile('dest/app.css.map', result.map);
        });
});
```
```
PS C:\Users\workstation\Documents\www-static> node app.js
(node:8760) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:124:9)
    at Object.fs.writeFile (fs.js:1244:14)
    at postcss.process.then.result (C:\Users\workstation\Documents\www-static\app.js:10:16)
(node:8760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
```
PS C:\Users\workstation\Documents\www-static> npm -v
5.6.0
PS C:\Users\workstation\Documents\www-static> node -v
v10.0.0
```
Could someone update the documentation or make it a bit more friendly ?
Kindest Regards.

**Comment by ai** [comment]
Sure. Do you want to send PR?

**Comment by coldtelling** [comment]
@ai Would love to, unfortunately I'm way too inexperienced !

**Comment by ai** [comment]
Done 6601a3e
