### ISSUE TITLE
CssSyntaxError: <css input>:1205:1: Unclosed block

### ISSUE THREAD

**Issue by Julia1996** [postcss/postcss#1208]
I use rtlcss, that uses your module. I have this error:
```
[06:31:00] Starting 'rtl'...

myproject/node_modules/rtlcss/node_modules/postcss/lib/lazy-result.js:248
        if (this.error) throw this.error;
                        ^
CssSyntaxError: <css input>:1205:1: Unclosed block
    at Input.error (myproject/node_modules/rtlcss/node_modules/postcss/lib/input.js:119:22)
    at Parser.unclosedBlock (myproject/node_modules/rtlcss/node_modules/postcss/lib/parser.js:515:26)
    at Parser.endFile (myproject/node_modules/rtlcss/node_modules/postcss/lib/parser.js:358:39)
    at Parser.parse (myproject/node_modules/rtlcss/node_modules/postcss/lib/parser.js:88:14)
    at parse (myproject/node_modules/rtlcss/node_modules/postcss/lib/parse.js:24:16)
    at new LazyResult (myproject/node_modules/rtlcss/node_modules/postcss/lib/lazy-result.js:70:24)
    at Processor.process (myproject/node_modules/rtlcss/node_modules/postcss/lib/processor.js:117:12)
    at DestroyableTransform._transform (myproject/node_modules/gulp-rtlcss/index.js:26:47)
    at DestroyableTransform.Transform._read (myproject/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (myproject/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
```

Every time line of code here `<css input>:1205:1: Unclosed block` is different. But my css in this places is OK. For example:
```
...
1203   line-height: 1.33;
1204 }
1205 .banner-type .banner-text h2 {
1206   font-size: 3.2rem;
1207   font-weight: 300;
1208   margin: 0;
1209 }
...
```
 Sometimes it works without any errors.

**Comment by ai** [comment]
Try to remove blocks of CSS to find the source.

Maybe the right is upper.

**Comment by ai** [comment]
I am cllosing issue since there was no answer
