### ISSUE TITLE
Error: Unsupported source map encoding charset=utf-8

### ISSUE THREAD

**Issue by benjrichardson** [postcss/postcss#1371]
I'm having some issues when I try to apply postcss transformations to a css file that was previously generated by dart-sass.

```
postcss css/**/*.css --dir css -u cssnano
Error: Unsupported source map encoding charset=utf-8
    at PreviousMap.decodeInline (/mnt/c/Users/Benjamin/Desktop/UmbracoCms.8.6.2/node_modules/postcss/lib/previous-map.js:122:11)
    at PreviousMap.loadMap (/mnt/c/Users/Benjamin/Desktop/UmbracoCms.8.6.2/node_modules/postcss/lib/previous-map.js:149:19)     
    at new PreviousMap (/mnt/c/Users/Benjamin/Desktop/UmbracoCms.8.6.2/node_modules/postcss/lib/previous-map.js:51:21)
    at new Input (/mnt/c/Users/Benjamin/Desktop/UmbracoCms.8.6.2/node_modules/postcss/lib/input.js:80:15)
    at parse (/mnt/c/Users/Benjamin/Desktop/UmbracoCms.8.6.2/node_modules/postcss/lib/parse.js:13:15)
    at new LazyResult (/mnt/c/Users/Benjamin/Desktop/UmbracoCms.8.6.2/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/mnt/c/Users/Benjamin/Desktop/UmbracoCms.8.6.2/node_modules/postcss/lib/processor.js:138:12)      
    at Processor.process (/mnt/c/Users/Benjamin/Desktop/UmbracoCms.8.6.2/node_modules/postcss/lib/processor.js:117:23)
    at rc.then (/mnt/c/Users/Benjamin/Desktop/UmbracoCms.8.6.2/node_modules/postcss-cli/index.js:217:10)
```

And the file in question:

```
body {
  display: flex;
  background: green;
  color: red;
  border-color: orange;
  border-width: 10px;
}

/*# sourceMappingURL=data:application/json;charset=utf-8,%7B%22version%22:3,%22sourceRoot%22:%22%22,%22sources%22:%5B%22../scss/mainStyles.scss%22%5D,%22names%22:%5B%5D,%22mappings%22:%22AAEA;EACI;EACA;EACA,OALK;EAML;EACA%22,%22file%22:%22mainStyles.css%22,%22sourcesContent%22:%5B%22$accent:%20red;%5Cr%5Cn%5Cr%5Cnbody%20%7B%5Cr%5Cn%20%20%20%20display:%20flex;%5Cr%5Cn%20%20%20%20background:%20green;%5Cr%5Cn%20%20%20%20color:%20$accent;%5Cr%5Cn%20%20%20%20border-color:%20orange;%5Cr%5Cn%20%20%20%20border-width:%2010px;%5Cr%5Cn%7D%22%5D%7D */
```

The error only seems to occur on embedded source maps.

**Comment by ai** [comment]
PostCSS does not support source map in this format.

I can add a new format in next 8.0 release.

**Comment by ai** [comment]
Done https://github.com/postcss/postcss/blob/ose/test/previous-map.test.ts#L99-L108

**Comment by ai** [comment]
We will release this change in the next 8.0 release.

You can speed up the release by talking with your company’s manager about supporting PostCSS:
https://opencollective.com/postcss/
