### ISSUE TITLE
8.0.9 to 8.1.1 - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Oreoz** [postcss/postcss#1433]
```js
// postcss.config.js
const autoprefixer = require("autoprefixer");
const tailwindcss = require("tailwindcss");

module.exports = {
  plugins: [tailwindcss("./tailwind.js"), autoprefixer],
};
```

```css
/* tailwind.css */
@tailwind base;
@tailwind components;
@tailwind utilities;

.react-rotating-text-cursor {
  animation: blinking-cursor 0.8s cubic-bezier(0.68, 0.01, 0.01, 0.99) 0s
    infinite;
}

@keyframes blinking-cursor {
  0% {
    opacity: 0;
  }
  50% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
```

When running `postcss src/styles/tailwind.css -o src/styles/app.css` after bumping the `postcss` version (and changing nothing else) from 8.0.9 to 8.1.1 I get the following error:

```sh
RangeError: Maximum call stack size exceeded
    at E:\workspace\website\src\styles\tailwind.css:1:1
    at E:\workspace\website\src\styles\tailwind.css:3:1
    at Function.keys (<anonymous>)
    at clone (E:\workspace\website\node_modules\autoprefixer\lib\prefixer.js:11:24)
    at clone (E:\workspace\website\node_modules\autoprefixer\lib\prefixer.js:23:17)
    at clone (E:\workspace\website\node_modules\autoprefixer\lib\prefixer.js:23:17)
    at clone (E:\workspace\website\node_modules\autoprefixer\lib\prefixer.js:23:17)
    at clone (E:\workspace\website\node_modules\autoprefixer\lib\prefixer.js:23:17)
    at clone (E:\workspace\website\node_modules\autoprefixer\lib\prefixer.js:23:17)
    at clone (E:\workspace\website\node_modules\autoprefixer\lib\prefixer.js:23:17)
    at clone (E:\workspace\website\node_modules\autoprefixer\lib\prefixer.js:23:17)
    at clone (E:\workspace\website\node_modules\autoprefixer\lib\prefixer.js:23:17) {
  postcssNode: <ref *1> Root {
    raws: { semicolon: false, after: '\r\n' },
    type: 'root',
    nodes: [
      [Comment], [Comment], [Comment], [Rule],    [Comment], [Comment],
      [Rule],    [Comment], [Rule],    [Comment], [Rule],    [Comment],
      [Comment], [Rule],    [Comment], [Rule],    [Comment], [Comment],
      [Rule],    [Comment], [Rule],    [Comment], [Rule],    [Comment],
      [Rule],    [Comment], [Rule],    [Comment], [Rule],    [Rule],
      [Rule],    [Comment], [Comment], [Rule],    [Comment], [Comment],
      [Rule],    [Comment], [Rule],    [Comment], [Rule],    [Comment],
      [Rule],    [Comment], [Rule],    [Comment], [Rule],    [Comment],
      [Rule],    [Comment], [Rule],    [Comment], [Rule],    [Comment],
      [Rule],    [Comment], [Rule],    [Comment], [Rule],    [Comment],
      [Rule],    [Comment], [Rule],    [Comment], [Rule],    [Comment],
      [Comment], [Rule],    [Comment], [Rule],    [Comment], [Comment],
      [Rule],    [Comment], [Rule],    [Comment], [Comment], [Rule],
      [Rule],    [Comment], [Rule],    [Rule],    [Rule],    [Comment],
      [Comment], [Rule],    [Comment], [Rule],    [Comment], [Rule],
      [Comment], [Rule],    [Rule],    [Rule],    [Rule],    [Rule],
      [Rule],    [Comment], [Rule],    [Comment],
      ... 3708 more items
    ],
    source: { input: [Input], start: [Object] },
    lastEach: 47,
    indexes: { '47': 308 },
    rawCache: {
      beforeComment: '',
      beforeRule: '\r\n',
      indent: '  ',
      beforeOpen: ' ',
      semicolon: true,
      beforeDecl: '\n',
      colon: ': ',
      beforeClose: '\n'
    },
    proxyCache: [Circular *1],
    _autoprefixerDisabled: false,
    _autoprefixerGridStatus: false,
    _autoprefixerPrefix: false,
    [Symbol(isClean)]: true
  }
}
```

Looks like an issue with `autoprefixer` under the hood.

Didn't see anything regarding this in the chat / issues. Sorry if it's already being addressed.

**Comment by Oreoz** [comment]
It was locked at 10.0.0 at the moment of the issue. It occurred in a dependabot PR.

**Comment by ai** [comment]
Can you update PostCSS to 8.1.1 and Autoprefixer to 10.0.1 and try again?

**Comment by Oreoz** [comment]
> Can you update PostCSS to 8.1.1 and Autoprefixer to 10.0.1 and try again?

Sure, I'll try that out shortly and report afterwards.

**Comment by Oreoz** [comment]
Looks good. https://github.com/Oreoz/website/pull/175/files

**Comment by Oreoz** [comment]
Thanks!
