### ISSUE TITLE
parser error using in postcss-loader work with less-loader under webpack5 

### ISSUE THREAD

**Issue by X-neuron** [postcss/postcss#1443]
Error comes from here :https://github.com/webpack-contrib/postcss-loader/issues/491 

Reproduce: https://github.com/X-neuron/webpack5antdtest

Discribe:  
when disable the postcss-loader ，after "npm run dev/build" it works fine, can see the correct result. so this can infer less-loader and css-loader works fine and include/ exclude logic maybe right.

in webpack/webpack.config.js

```
const getStyleLoaders = (cssOptions, preProcessor) => {
    const loaders = [
      isEnvDevelopment && require.resolve("style-loader"),
      isEnvProduction && {
        loader: MiniCssExtractPlugin.loader,
        // css is located in `static/css`, use '../../' to locate index.html folder
        // in production `paths.publicUrlOrPath` can be a relative path
        options: paths.publicUrlOrPath.startsWith(".")
          ? { publicPath: "../../"}
          : { },
      },
      {
        loader: require.resolve("css-loader"),
        options: cssOptions,
      },
      false && {
        loader: "postcss-loader",
        options: {
          // Necessary for external CSS imports to work
          // https://github.com/facebook/create-react-app/issues/2677
          postcssOptions:{
            // Options for PostCSS as we reference these options twice
            // Adds vendor prefixing based on your specified browser support in
            ident: "postcss",
            plugins: [
              require("postcss-flexbugs-fixes"),
              require("postcss-preset-env")({
                autoprefixer: {
                  flexbox: "no-2009",
                },
                stage: 3,
              }),
              // Adds PostCSS Normalize as the reset css with default options,
              // so that it honors browserslist config in package.json
              // which in turn let's users customize the target behavior as per their needs.
              postcssNormalize(),
            ],
          },
          sourceMap: isEnvProduction ? shouldUseSourceMap : isEnvDevelopment,
        },
      },
    ].filter(Boolean);
    if (preProcessor) {
      loaders.push(
        // https://github.com/webpack-contrib/postcss-loader/issues/477
        // {
        //   loader: require.resolve("resolve-url-loader"),
        //   options: {
        //     sourceMap: isEnvProduction ? shouldUseSourceMap : isEnvDevelopment,
        //   },
        // },
        {
          loader: require.resolve(preProcessor),
          options: preProcessor === "less-loader"
            ? {
              sourceMap: isEnvProduction && shouldUseSourceMap,
              lessOptions: {
                javascriptEnabled: true,
              }
            } // less loader 6.0.0 支持antd
            : {
              sourceMap: isEnvProduction && shouldUseSourceMap,
            },
        }
      );
    }
    // console.log(loaders)
    return loaders;
  };
```
but when enable the postcss-loader，error encountered

```
(3:0) E:\project\antdwebpack5test\index.less Unnecessary curly bracket

  1 | /* stylelint-disable at-rule-empty-line-before,at-rule-name-space-after,at-rule-no-unknown */
  2 | /* stylelint-disable no-duplicate-selectors */
> 3 | /* stylelint-disable */
    |                                 ^
  4 | /* stylelint-disable declaration-bang-space-before,no-duplicate-selectors,string-no-newline */
  5 | .menu :global(.anticon) {

    at processResult (E:\project\antdwebpack5test\node_modules\webpack\lib\NormalModule.js:576:19)
    at E:\project\antdwebpack5test\node_modules\webpack\lib\NormalModule.js:669:5
    at E:\project\antdwebpack5test\node_modules\loader-runner\lib\LoaderRunner.js:397:11
    at E:\project\antdwebpack5test\node_modules\loader-runner\lib\LoaderRunner.js:252:18
    at context.callback (E:\project\antdwebpack5test\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (E:\project\antdwebpack5test\node_modules\postcss-loader\dist\index.js:101:7)
 @ ./src/components/SelectLang/index.jsx 3:91-124 5:50-61 7:609-624
 @ ./src/app.jsx 4:163-211 5:1080-1090
 @ ./src/index.jsx 4:44-67 13:149-152

```
So can we treat it as a postcss's parser bug, can not compatible with less-loader v7?

**Comment by ai** [comment]
`Unnecessary curly bracket` is not an issue from PostCSS.

You should go to webpack Slack or StackOverflow and ask a question about the right configuration.

Or try to disable all PostCSS or remove all CSS input to find what exactly trigger an issue in Less parser.

**Comment by X-neuron** [comment]
thanks very much~
