### ISSUE TITLE
Angular build failing on 8.1.5

### ISSUE THREAD

**Issue by baxelson12** [postcss/postcss#1457]
Good morning,
it seems that a new version was just released.  After updating im receiving a handful of errors.

```
ERROR in ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "postcss-scss" syntax failed: Package subpath './lib/stringifier' is not defined by "exports" in G:\WebDev\nestjs\ptrack\employee-client\node_modules\postcss-scss\node_modules\postcss\package.json

(@G:\WebDev\nestjs\ptrack\employee-client\src\styles.scss)
    at Object.emitError (G:\WebDev\nestjs\ptrack\employee-client\node_modules\webpack\lib\NormalModule.js:173:6)
    at getPostcssOptions (G:\WebDev\nestjs\ptrack\employee-client\node_modules\postcss-loader\dist\utils.js:252:21)
    at Object.loader (G:\WebDev\nestjs\ptrack\employee-client\node_modules\postcss-loader\dist\index.js:64:36)

ERROR in Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'parse' of undefined
    at new LazyResult (G:\WebDev\nestjs\ptrack\employee-client\node_modules\postcss\lib\lazy-result.js:57:18)
    at Processor.<anonymous> (G:\WebDev\nestjs\ptrack\employee-client\node_modules\postcss\lib\processor.js:138:12)
    at Processor.process (G:\WebDev\nestjs\ptrack\employee-client\node_modules\postcss\lib\processor.js:117:23)
    at Object.loader (G:\WebDev\nestjs\ptrack\employee-client\node_modules\postcss-loader\dist\index.js:94:51)
```

package.json

```
  "dependencies": {
    "@angular/animations": "~10.2.0",
    "@angular/cli": "~10.2.0",
    "@angular/common": "~10.2.0",
    "@angular/compiler": "~10.2.0",
    "@angular/compiler-cli": "~10.2.0",
    "@angular/core": "~10.2.0",
    "@angular/forms": "~10.2.0",
    "@angular/platform-browser": "~10.2.0",
    "@angular/platform-browser-dynamic": "~10.2.0",
    "@angular/router": "~10.2.0",
    "@angular/service-worker": "~10.2.0",
    "@zxing/browser": "0.0.5",
    "@zxing/library": "^0.18.3",
    "@zxing/ngx-scanner": "3.0.0",
    "jwt-decode": "^3.0.0",
    "ng-qrcode": "^4.0.1",
    "ngx-mask": "^10.0.4",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1002.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ngx-build-plus": "latest",
    "ngx-tailwind": "^0.5.1",
    "postcss-import": "12.0.1",
    "postcss-loader": "latest",
    "postcss-scss": "latest",
    "protractor": "~7.0.0",
    "tailwindcss": "latest",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
```

Reverting resolves the error.
Thank you.

**Comment by sgrezza** [comment]
I just created a fresh **React** app, and I'm also getting errors trying to run `yarn start`.

```
Error: Cannot find module '/Users/sgrezza/dev/reactProjects/serverMore/node_modules/postcss-safe-parser/node_modules/postcss/lib/tokenize'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:927:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:920:15)
    at resolveExports (node:internal/modules/cjs/loader:456:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:496:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:887:27)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (/Users/sgrezza/dev/reactProjects/serverMore/node_modules/postcss-safe-parser/lib/safe-parser.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1083:30) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/sgrezza/dev/reactProjects/serverMore/node_modules/postcss-safe-parser/node_modules/postcss/package.json'
}
```

Package.json
```
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.53",
    "@types/react-dom": "^16.9.8",
    "ky": "^0.24.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.0",
    "typescript": "^4.0.3",
    "web-vitals": "^0.2.4"
  },
```

I can't revert because I just started the project, so I can't give you a working case.

**Comment by ai** [comment]
@ShenHongFei seems like the fix was break Angular and CRA

**Comment by clydin** [comment]
This also breaks Webpack's css-loader which imports the `package.json` from postcss.
https://github.com/webpack-contrib/css-loader/blob/c1ca32f068a989060f667b7ad5c81df1a0a21f10/src/index.js#L7

**Comment by ai** [comment]
The fix was released in PostCSS 8.1.6

**Comment by yurique** [comment]
updating `8.1.4` to `8.1.5` (keeping everything else without any changes) causes this:

```
87% sealing module hashingTypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:84:11)
    at BulkUpdateDecorator.update (/path/to/the/project/node_modules/webpack/lib/util/createHash.js:49:14)
    at NormalModule.updateHash (/path/to/the/project/node_modules/webpack/lib/NormalModule.js:1048:8)
    at Compilation.createModuleHashes (/path/to/the/project/node_modules/webpack/lib/Compilation.js:2618:12)
    at /path/to/the/project/node_modules/webpack/lib/Compilation.js:1956:11
    at eval (eval at create (/path/to/the/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at /path/to/the/project/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js:449:32
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

It's a webpack project with postcss-loader:

```js
{
        test: /\.css$/,
        use: [
          {
            loader: ExtractCssChunks.loader,
            options: {
              filename: '[name].[contenthash:8].[ext]',
            },
          },
          {
            loader: 'css-loader',
            options: { importLoaders: 1 },
          },
          {
            loader: 'postcss-loader',
          },
        ],
      }
```

**Comment by sgrezza** [comment]
Running `yarn upgrade` after you released 8.1.6 got me working. Thanks!

**Comment by yurique** [comment]
10 minutes from an issue being reported to the fix getting released. I'm astonished. Just WOW!

**Comment by ai** [comment]
Thanks =^_^=

The best way to support PostCSS development is [our OpenCollective](https://opencollective.com/postcss/).
