### ISSUE TITLE
node.addToError/node.toProxy is not a function

### ISSUE THREAD

**Issue by barisusakli** [postcss/postcss#1464]
Started recently, I think after 8.1.x

```
TypeError: node.addToError is not a function
    at LazyResult.handleError (/home/saas/nodebb/node_modules/postcss/lib/lazy-result.js:294:22)
    at LazyResult.visitTick (/home/saas/nodebb/node_modules/postcss/lib/lazy-result.js:439:20)
    at LazyResult.runAsync (/home/saas/nodebb/node_modules/postcss/lib/lazy-result.js:349:30)

TypeError: node.toProxy is not a function
    at LazyResult.visitTick (/home/saas/nodebb/node_modules/postcss/lib/lazy-result.js:437:29)
    at LazyResult.runAsync (/home/saas/nodebb/node_modules/postcss/lib/lazy-result.js:349:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
Happens during building css 

```
nodebb@1.15.3-beta.0 /home/saas/nodebb
├── UNMET DEPENDENCY postcss@8.1.8
├─┬ UNMET DEPENDENCY postcss-clean@1.1.0
│ └── UNMET DEPENDENCY postcss@6.0.23
└─┬ UNMET DEPENDENCY sanitize-html@2.1.2
  └── UNMET DEPENDENCY postcss@8.1.7
```
Let me know if you need anything else.

**Comment by ai** [comment]
Can you try removing `postcss-clean`?

Very likely that it adds old PostCSS nodes to AST.

**Comment by barisusakli** [comment]
When I remove postcss-clean and change the code to not use it I get a different error this time from autoprefixer.

The changed code
```
function buildCSS(data, callback) {
	less.render(data.source, {
		paths: data.paths,
		javascriptEnabled: true,
	}, function (err, lessOutput) {
		if (err) {
			// display less parser errors properly
			return callback(new Error(String(err)));
		}

		postcss(data.minify ? [
			autoprefixer
			// disabled for testing
                        // clean({
			// 	processImportFrom: ['local'],
			// }),
		] : [autoprefixer]).process(lessOutput.css, {
			from: undefined,
		}).then(function (result) {
			process.nextTick(callback, null, { code: result.css });
		}).catch(function (err) {
			process.nextTick(callback, err);
		});
	});
}
```

The error
```
RangeError: Maximum call stack size exceeded
    at <input css X6XQK_>:1:1
    at <input css X6XQK_>:10366:3
    at Function.keys (<anonymous>)
    at clone (/home/saas/nodebb/node_modules/autoprefixer/lib/prefixer.js:11:24)
    at clone (/home/saas/nodebb/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/home/saas/nodebb/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/home/saas/nodebb/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/home/saas/nodebb/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/home/saas/nodebb/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/home/saas/nodebb/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/home/saas/nodebb/node_modules/autoprefixer/lib/prefixer.js:23:17)
    at clone (/home/saas/nodebb/node_modules/autoprefixer/lib/prefixer.js:23:17)
```

If I downgrade `postcss` to 8.0.9 then it works with no other changes.

**Comment by ai** [comment]
Seems like you use the old Autoprefixer version. Double-check that it is the latest version.

**Comment by barisusakli** [comment]
Hmm installed autoprefixer was at 10.0.0 even though package.json had "autoprefixer": "^10.0.0" I manually installed 10.0.2 and it seems resolved now. Not sure why yarn/npm didn't install 10.0.2.

Everything seems to be working with these dependencies now 

```
saas@try:~/nodebb$ yarn list --pattern autoprefixer
yarn list v1.21.1
└─ autoprefixer@10.0.2
Done in 2.06s.
saas@try:~/nodebb$ yarn list --pattern postcss
yarn list v1.21.1
├─ postcss-clean@1.1.0
│  └─ postcss@6.0.23
├─ postcss-value-parser@4.1.0
├─ postcss@8.1.8
└─ sanitize-html@2.0.0
   └─ postcss@8.1.1
Done in 1.97s.
```

Thanks for the help.
