### ISSUE TITLE
TypeError: Invalid PostCSS Plugin found: [0]

### ISSUE THREAD

**Issue by AlexWayfer** [postcss/postcss#1491]
```
> postcss assets/styles/ -d compiled/styles/ --base assets/styles/ --ext=css

TypeError: Invalid PostCSS Plugin found: [0]
    at /home/alex/.config/yarn/global/node_modules/postcss-load-plugins/lib/plugins.js:32:17
    at Array.forEach (<anonymous>)
    at plugins (/home/alex/.config/yarn/global/node_modules/postcss-load-plugins/lib/plugins.js:21:15)
    at /home/alex/.config/yarn/global/node_modules/postcss-load-config/index.js:64:18
    at async Promise.all (index 0)
npm ERR! code 1
npm ERR! path /home/alex/Projects/alexwayfer.name
npm ERR! command failed
npm ERR! command sh -c postcss assets/styles/ -d compiled/styles/ --base assets/styles/ --ext=css

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2020-12-17T23_41_02_484Z-debug.log
npm ERR! code 1
npm ERR! path /home/alex/Projects/alexwayfer.name
npm ERR! command failed
npm ERR! command sh -c npm run build:styles && npm run build:scripts

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2020-12-17T23_41_02_536Z-debug.log
npm ERR! code 1
npm ERR! path /home/alex/Projects/alexwayfer.name
npm ERR! command failed
npm ERR! command sh -c npm run lint && npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2020-12-17T23_41_02_584Z-debug.log
```

The freshest packages (`npm outdated` output is empty), presumably after https://github.com/AlexWayfer/alexwayfer.name/pull/57

I saw #1410, but it seems unrelated.

**Comment by ai** [comment]
Check `npm ls` you have PostCSS 7 somewhere, which can't run PostCSS 8 plugin.

We have a better error message in core, but many runners have own wrapper to load plugins and show this bad message.

**Comment by AlexWayfer** [comment]
> Check `npm ls` you have PostCSS 7 somewhere, which can't run PostCSS 8 plugin.

```
> git co 581b84df530a4ce384fb6c9153d49fafbcdee5fc
...

> npm i
...

> npm outdated                                                                                                       18 Dec 03:16:08 
Package         Current  Wanted  Latest  Location                     Depended by
postcss-mixins    7.0.1   7.0.2   7.0.2  node_modules/postcss-mixins  alexwayfer.name

> npm ls
alexwayfer.name@ /home/alex/Projects/alexwayfer.name
├── @rollup/plugin-node-resolve@11.0.1
├── autoprefixer@10.1.0
├── date-fns@2.16.1
├── eslint@7.15.0
├── postcss-at-rules-variables@0.2.1
├── postcss-mixins@7.0.1
├── postcss-nested@5.0.3
├── postcss@8.2.1
├── remark-cli@9.0.0
├── remark-gfm@1.0.0
├── remark-preset-lint-recommended@5.0.0
├── rollup@2.35.1
├── stylelint-config-standard@20.0.0
├── stylelint-no-unsupported-browser-features@4.1.4
├── stylelint@13.8.0
└── yaml@1.10.0
```

I see no  PostCSS 7 here.

**Comment by ai** [comment]
This is only top level. Some tool used PostCSS 7 inside.
