### ISSUE TITLE
Support for "@supports selector"

### ISSUE THREAD

**Issue by dvoytenko** [postcss/postcss#1520]
The `@supports selector() {}` form is now supported in Chromium and Mozilla-based browsers. It'd be great if it was supported in PostCSS as well.

https://developer.mozilla.org/en-US/docs/Web/CSS/@supports

**Comment by Semigradsky** [comment]
@dvoytenko what do you means? It works like a charm https://astexplorer.net/#/gist/7c51d2b6aecce8a0c6f2642616343187/241532feecc453342e26b740a39dc6b252796c6d

**Comment by Semigradsky** [comment]
@dvoytenko what do you means? PostCSS can parse it.

**Comment by ai** [comment]
Are you asking about adding `@supports selector` support to [Autoprefixer](https://github.com/postcss/autoprefixer)?

**Comment by dvoytenko** [comment]
@ai yep, you're right. This appears to be an Autoprefixer request. Here's the error stack I'm seeing:

```
    at Rule.normalize (~/node_modules/postcss/lib/container.js:334:13)
    at Rule.append (~/node_modules/postcss/lib/container.js:166:24)
    at Supports.virtual (~/node_modules/autoprefixer/lib/supports.js:71:10)
    at Supports.prefixed (~/node_modules/autoprefixer/lib/supports.js:79:21)
    at ~/node_modules/autoprefixer/lib/supports.js:239:29
    at Array.map (<anonymous>)
    at Supports.add (~/node_modules/autoprefixer/lib/supports.js:237:18)
    at Supports.process (~/node_modules/autoprefixer/lib/supports.js:262:16)
    at ~/node_modules/autoprefixer/lib/processor.js:67:27
    at ~/node_modules/postcss/lib/container.js:138:18
    at ~/node_modules/postcss/lib/container.js:74:18
```

And the example that triggers it is:

```
@supports selector(:where(A)) {
  :where(A) {
     ...
  }
}
```

Should I move this issue to Autoprefixer repo?
