### ISSUE TITLE
Getting ERR_PACKAGE_PATH_NOT_EXPORTED error on npm run build

### ISSUE THREAD

**Issue by bildungsroman** [postcss/postcss#1586]
I have a dependency that relies on `postcss-colormin` as a dependency, and it's breaking my entire build as of a few hours ago. Any help would be appreciated!

Here is the entire error:

```bash

styles.ed559fef764fc0c48382.css from Css Minimizer
--
956 | Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugins/names' is not defined by "exports" in /codebuild/output/src413139041/src/node_modules/colord/package.json
957 | at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
958 | at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
959 | at resolveExports (internal/modules/cjs/loader.js:444:36)
960 | at Function.Module._findPath (internal/modules/cjs/loader.js:484:31)
961 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:818:27)
962 | at Function.Module._load (internal/modules/cjs/loader.js:687:27)
963 | at Module.require (internal/modules/cjs/loader.js:903:19)
964 | at require (internal/modules/cjs/helpers.js:74:18)
965 | at Object.&lt;anonymous&gt; (/codebuild/output/src413139041/src/node_modules/postcss-colormin/dist/colours.js:10:37)
966 | at Module._compile (internal/modules/cjs/loader.js:1015:30)
967 | error Generating JavaScript bundles failed
968 | &nbsp;
969 | styles.f692443edacb1ff312fd.css from Css Minimizer
970 | Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugins/names' is not defined by "exports" in /codebuild/output/src413139041/src/node_modules/colord/package.json
971 | at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
972 | at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
973 | at resolveExports (internal/modules/cjs/loader.js:444:36)
974 | at Function.Module._findPath (internal/modules/cjs/loader.js:484:31)
975 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:818:27)
976 | at Function.Module._load (internal/modules/cjs/loader.js:687:27)
977 | at Module.require (internal/modules/cjs/loader.js:903:19)
978 | at require (internal/modules/cjs/helpers.js:74:18)
979 | at Object.&lt;anonymous&gt; (/codebuild/output/src413139041/src/node_modules/postcss-colormin/dist/colours.js:10:37)
980 | at Module._compile (internal/modules/cjs/loader.js:1015:30)
```

**Comment by bildungsroman** [comment]
The apparently offending line is found in `postcss-colormin/dist/colours.js` at line 10:

```javascript
var _keywords = _interopRequireDefault(require("./keywords.json"));
```

**Comment by ai** [comment]
Seems like error came from `postcss-colormin`. It is part of `cssnano` project.

You need to report and issue to `cssnano`, since I am not a maintainer for that project.

https://github.com/cssnano/cssnano/issues

**Comment by bildungsroman** [comment]
Ok, sorry for the confusion, I'll try them.
