### ISSUE TITLE
css clamp() syntax error

### ISSUE THREAD

**Issue by LukaszJaro** [postcss/postcss#1607]
Hi,

I'm using custom css properties, they are imported into the relevant stylesheets with `@import '_custom-properties.css';`

However when using clamp() it causes error. Any ideas what is going on? thanks!

CSS
```
--font-size-larger: clamp(1.25rem, 0.9423rem + 1.5385vw, 1.75rem);
--font-size-huge: clamp(1.5rem, 1.0294rem + 2.3529vw, 2.5rem);
```

Error
```
[08:51:01] 'styles' errored after 16 s
[08:51:01] ParserError in plugin "gulp-postcss"
Message:
    Syntax Error at line: 1, column 26
Details:
    fileName: C:\project\assets\css\src\content.css

Stack:
ParserError: Syntax Error at line: 1, column 26
    at Parser.error (C:\project\node_modules\postcss-values-parser\lib\parser.js:127:11)
    at Parser.operator (C:\project\node_modules\postcss-values-parser\lib\parser.js:183:18)
    at Parser.parseTokens (C:\project\node_modules\postcss-values-parser\lib\parser.js:245:14)
    at Parser.loop (C:\project\node_modules\postcss-values-parser\lib\parser.js:132:12)
    at Parser.parse (C:\project\node_modules\postcss-values-parser\lib\parser.js:51:17)
    at parse (C:\project\node_modules\postcss-custom-properties\src\lib\postcss-values-parser.js:4:29)
    at parse (C:\project\node_modules\postcss-custom-properties\src\lib\get-custom-properties-from-root.js:25:37)
    at Array.forEach (<anonymous>)
    at forEach (C:\project\node_modules\postcss-custom-properties\src\lib\get-custom-properties-from-root.js:20:23)
    at Array.forEach (<anonymous>)
```

**Comment by LukaszJaro** [comment]
It appears to break when I use math inside clamp

**Comment by ai** [comment]
`ParserError` is not an error from PostCSS core parser.

You should open an issue in `postcss-values-parser` since this plugin use an additional parser for CSS values.
