### ISSUE TITLE
Error: [object Object] is not a PostCSS plugin

### ISSUE THREAD

**Issue by sh4rov** [postcss/postcss#1623]
Reinstalled linux. Downloaded my build, installed packages, run ... error.

**Terminal**
```
npx gulp                                                                                                             ─╯
[13:46:32] Requiring external module @babel/register
[13:46:34] Using gulpfile ~/front/frontkit/gulpfile.babel.js
[13:46:34] Starting 'default'...
[13:46:34] Starting 'styles'...
[13:46:34] Starting 'views'...
[13:46:34] Starting 'scripts'...
[13:46:34] Starting 'fonts'...
[13:46:34] Starting 'images'...
[13:46:34] Starting 'video'...
[13:46:34] 'styles' errored after 218 ms
[13:46:34] Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/kek/front/frontkit/node_modules/postcss/lib/processor.es6:108:23)
    at new Processor (/home/kek/front/frontkit/node_modules/postcss/lib/processor.es6:35:29)
    at postcss (/home/kek/front/frontkit/node_modules/postcss/lib/postcss.es6:34:12)
    at cssnanoPlugin (/home/kek/front/frontkit/node_modules/cssnano/dist/index.js:145:31)
    at styles (/home/kek/front/frontkit/gulpfile.babel.js/tasks/styles.js:19:5)
    at bound (domain.js:416:15)
    at runBound (domain.js:427:12)
    at asyncRunner (/home/kek/front/frontkit/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[13:46:34] 'default' errored after 231 ms
```

**package.json**

```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "gulp"
  },
  "browserslist": [
    "last 1 version",
    "> 1%",
    "IE 11"
  ],
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "@babel/preset-env": "^7.15.0",
    "@babel/register": "^7.15.3",
    "autoprefixer": "^10.3.1",
    "browser-sync": "^2.27.5",
    "cssnano": "^5.0.7",
    "del": "^6.0.0",
    "fs": "^0.0.1-security",
    "gh-pages": "^3.2.3",
    "gulp": "^4.0.2",
    "gulp-babel": "^8.0.0",
    "gulp-changed": "^4.0.3",
    "gulp-concat": "^2.6.1",
    "gulp-dart-sass": "^1.0.2",
    "gulp-debug": "^4.0.0",
    "gulp-eslint": "^6.0.0",
    "gulp-file-include": "^2.3.0",
    "gulp-group-css-media-queries": "^1.2.2",
    "gulp-newer": "^1.4.0",
    "gulp-plumber": "^1.2.1",
    "gulp-postcss": "^9.0.0",
    "gulp-remember": "^1.0.1",
    "gulp-rename": "^2.0.0",
    "gulp-strip-comments": "^2.5.2",
    "gulp-terser": "^2.0.1",
    "path": "^0.12.7",
    "prettier": "2.3.2",
    "webpcss": "^1.3.4"
  },
  "description": "",
  "dependencies": {
    "normalize.css": "^8.0.1",
    "sass-rem": "^3.0.0"
  }
}

```
**gulp task**

```
import { src, dest, lastRun } from 'gulp'
import sass from 'gulp-dart-sass'
import postcss from 'gulp-postcss'
import cssnano from 'cssnano'
import autoprefixer from 'autoprefixer'
import changed from 'gulp-changed'
import groupMedia from 'gulp-group-css-media-queries'
import rename from 'gulp-rename'
import remember from 'gulp-remember'
import plumber from 'gulp-plumber'
import debug from 'gulp-debug'

import paths from '../paths'

const styles = () => {

  const plugins = [
    autoprefixer(),
    cssnano()
  ];

  return src(paths.styles.main, { sourcemaps: true })
    .pipe(plumber())
    .pipe(debug())
    .pipe(sass.sync().on('error', sass.logError))
    .pipe(postcss(plugins))
    .pipe(groupMedia())
    .pipe(
      rename({
        suffix: '.min',
      })
    )
    .pipe(dest(paths.styles.dist, { sourcemaps: '.' }))
}

module.exports = styles;
```

**Comment by ai** [comment]
Seems like you have PostCSS 7 somewhere in dependencies. Check tree by `npm ls`.

I am closing this issue since I can’t help with environment problems. Open an issue if you need something more specific about PostCSS core API.

**Comment by sh4rov** [comment]
> Seems like you have PostCSS 7 somewhere in dependencies. Check tree by `npm ls`.
> 
> I am closing this issue since I can’t help with environment problems. Open an issue if you need something more specific about PostCSS core API.

Cheked `npm ls`. Показало `UNMET PEER DEPENDENCY postcss@^8.1.0 `. Then I ran the command `npm install postcss@^8.1.0` and everything was solved. Thanks for your reply!
