### ISSUE TITLE
 Cannot read property '_autoprefixerDisabled' of undefined

### ISSUE THREAD

**Issue by airyland** [postcss/postcss#164]
Nice tool but I ran into an error.

```javascript
var postcss = require('gulp-postcss');

gulp.task('www',function(){
	var processors = [
		require('autoprefixer-core'),
		require('csswring')
	];
	gulp.src('./www/css/2014.css')
	.pipe(postcss(processors))
	.pipe(gulp.dest('./www/css'));
});
```

```bash
[10:30:41] Finished 'www' after 147 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property '_autoprefixerDisabled' of undefined
    at Processor.disabled (e:\source\node_modules\autoprefixer-core\lib\processo
r.js:133:15)
    at Processor.disabled (e:\source\node_modules\autoprefixer-core\lib\processo
r.js:151:50)
    at Processor.disabled (e:\source\node_modules\autoprefixer-core\lib\processo
r.js:151:50)
    at Processor.disabled (e:\source\node_modules\autoprefixer-core\lib\processo
r.js:151:50)
    at e:\source\node_modules\autoprefixer-core\lib\processor.js:102:21
    at e:\source\node_modules\postcss\lib\container.js:157:22
    at e:\source\node_modules\postcss\lib\container.js:127:18
    at Rule.Container.each (e:\source\node_modules\postcss\lib\container.js:105:
14)
    at Rule.Container.eachInside (e:\source\node_modules\postcss\lib\container.j
s:126:15)
    at e:\source\node_modules\postcss\lib\container.js:130:22
```

**Comment by ai** [comment]
Problem is because Autoprefixer expects PostCSS 3.0 and CSSWring uses PostCSS 4.0.

Downgrade gulp-postcss and csswring until Autoprefixer will be updated to new PostCSS.

We try to find some better solution here: https://github.com/w0rm/gulp-postcss/issues/14
