### ISSUE TITLE
MapGenerator error

### ISSUE THREAD

**Issue by itsthesteve** [postcss/postcss#1684]
With a fresh installation, errors are thrown with basic arguments.

Repro:

- Install `npm i -D postcss postcss-cli`
- Create NPM script: `postcss test.css -o output.css`

Versions installed-

```
"postcss": "^8.4.2",
"postcss-cli": "^9.0.2",
```

Running the script yields the following error:

```
TypeError: this.css.replace is not a function
    at MapGenerator.clearAnnotation (<home-dir-removed>/node_modules/postcss/lib/map-generator.js:88:27)
    at MapGenerator.generate (<home-dir-removed>/node_modules/postcss/lib/map-generator.js:316:10)
    at new NoWorkResult (<home-dir-removed>/node_modules/postcss/lib/no-work-result.js:32:46)
    at Processor.process (<home-dir-removed>/node_modules/postcss/lib/processor.js:26:14)
    at file://<home-dir-removed>/node_modules/postcss-cli/index.js:248:10
    at async Promise.all (index 0)
```

Locking the `postcss` version in package.json to 8.3.0 works as expected.

Node v14.15.3
MacOS 11.6

**Comment by ai** [comment]
Try PostCSS 8.4.3

**Comment by ai** [comment]
Closing since there is no report from other users and seems like the error was fixed
