### ISSUE TITLE
Error: PostCSS plugin postcss-custom-media requires PostCSS 8. 

### ISSUE THREAD

**Issue by Awilum** [postcss/postcss#1687]
I have error when I try to run `gulp build`

**Env**
node: v16.9.1
npm: 7.21.1
gulp: 
CLI version: 2.3.0
Local version: 4.0.2

```
[18:46:33] Error in plugin "gulp-postcss"
Message:
    PostCSS plugin postcss-custom-media requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
Details:
    fileName: /Applications/MAMP/htdocs/frontend/glowycss/src/glowy.css
    domainEmitter: [object Object]
    domainThrown: false

Stack:
Error: PostCSS plugin postcss-custom-media requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Applications/MAMP/htdocs/frontend/glowycss/node_modules/gulp-postcss/node_modules/postcss/lib/processor.js:167:15)
    at new Processor (/Applications/MAMP/htdocs/frontend/glowycss/node_modules/gulp-postcss/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Applications/MAMP/htdocs/frontend/glowycss/node_modules/gulp-postcss/node_modules/postcss/lib/postcss.js:55:10)
    at /Applications/MAMP/htdocs/frontend/glowycss/node_modules/gulp-postcss/index.js:50:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[18:46:33] 'build' errored after 36 ms
```

package.json

```
  "devDependencies": {
    "gulp": "github:gulpjs/gulp",
    "gulp-concat": "^2.6.1",
    "gulp-cssnano": "^2.1.3",
    "gulp-postcss": "^8.0.0",
    "gulp-rename": "^1.4.0",
    "gulp-size": "^3.0.0",
    "postcss": "^8.4.4",
    "postcss-cli": "^9.0.2",
    "postcss-custom-media": "^8.0.0",
    "postcss-import": "^12.0.1",
    "postcss-loader": "^4.1.0"
  }
  ```
  
Any ideas how to fix this ?

**Comment by Awilum** [comment]
Fixed: https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users#gulp
