### ISSUE TITLE
TypeError: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by MoOx** [postcss/postcss#169]
I were trying to upgrade postcss-import to postcss v4.
I bump postcss v4 in package.json, update `childs` to `nodes` but where thinking that would be enough :/

In addition [the weird behavior I got](https://github.com/postcss/postcss-import/issues/16#issuecomment-71166687) with `between` being modified in some places (but not everywhere) I'm getting this issue that seems related to the stringify process. Can't find a easy way to trace this issue from the stack trace.

I'm getting this issue from [postcss-import 3td test ("ignore")](https://github.com/postcss/postcss-import/blob/5e50144f73c3e5cc0f4bcd405e5cd837fc1f2112/test/index.js#L37).

```
/.../postcss/import/node_modules/tape/index.js:75
        throw err
              ^
TypeError: Cannot read property 'parent' of undefined
    at /.../postcss/import/node_modules/postcss/lib/node.js:271:39
    at /.../postcss/import/node_modules/postcss/lib/container.js:132:20
    at Root.Container.each (/.../postcss/import/node_modules/postcss/lib/container.js:110:16)
    at Root.Container.eachInside (/.../postcss/import/node_modules/postcss/lib/container.js:131:17)
    at AtRule.Node.style (/.../postcss/import/node_modules/postcss/lib/node.js:270:10)
    at AtRule.Node.style (/.../postcss/import/node_modules/postcss/lib/node.js:348:25)
    at AtRule.Container.stringifyBlock (/.../postcss/import/node_modules/postcss/lib/container.js:57:23)
    at AtRule.stringify (/.../postcss/import/node_modules/postcss/lib/at-rule.js:66:12)
    at Root.Container.stringifyContent (/.../postcss/import/node_modules/postcss/lib/container.js:50:21)
    at Root.stringify (/.../postcss/import/node_modules/postcss/lib/root.js:92:10)
```

Any idea on this issue (that looks like a bug)?

**Comment by ai** [comment]
Hm. I add extra check to fix this problem. https://github.com/postcss/postcss/commit/7e1b183d841a426dfa0260d7e8188539a6a126d3

Can you test a master?

**Comment by MoOx** [comment]
Getting the same issue with 4.0.2

```
/.../import/node_modules/tape/index.js:75
        throw err
              ^
TypeError: Cannot read property 'parent' of undefined
    at /.../import/node_modules/postcss/lib/node.js:361:31
    at /.../import/node_modules/postcss/lib/container.js:155:24
    at Root.each (/.../import/node_modules/postcss/lib/container.js:128:20)
    at Root.eachInside (/.../import/node_modules/postcss/lib/container.js:154:21)
    at AtRule.style (/.../import/node_modules/postcss/lib/node.js:359:16)
    at AtRule.style (/.../import/node_modules/postcss/lib/node.js:439:31)
    at AtRule.stringifyBlock (/.../import/node_modules/postcss/lib/container.js:65:27)
    at AtRule.stringify (/.../import/node_modules/postcss/lib/at-rule.js:73:16)
    at Root.stringifyContent (/.../import/node_modules/postcss/lib/container.js:53:25)
    at Root.stringify (/.../import/node_modules/postcss/lib/root.js:109:14)
``

**Comment by ai** [comment]
@MoOx very strange. Maybe you broke AST? Does all nodes has correct `parent` property? You mention that you avoid to use `clone()` or `move()`.

**Comment by MoOx** [comment]
Well nevermind, it seems my node_modules/postcss was weird.
Closing for now.
