### ISSUE TITLE
Syntax error in calc and var

### ISSUE THREAD

**Issue by super-kamil** [postcss/postcss#1704]
Hi,

I am not sure if this is a postcss issue.

```scss
:root {
    --spacer: 1rem;
}

.my-class {
    margin-top: calc(var(--spacer) * -1);
}
```

This will fail with the following syntax error:

```
ERROR in ./cms/elements/myElement.vue?vue&type=style&index=0&id=9122fbb2&lang=scss&scoped=true& (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./cms/elements/myElement.vue?vue&type=style&index=0&id=9122fbb2&lang=scss&scoped=true&)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: x, column x
```

node: 16.13.2
postcss "^7.0.32"
postcss-import "^12.0.1"
postcss-import-resolver "^2.0.0"
postcss-loader "^3.0.0"
postcss-preset-env "^6.7.0"
postcss-url "^8.0.0"

**Comment by ai** [comment]
Sorry, this error (according to error message) is not from PostCSS core parser.

Hard to say about the source. It could be from internal parser of some PostCSS plugin or from additional parser in your build tool.

**Comment by super-kamil** [comment]
Thanks. Here is the full error. Any idea where to report it? Maybe css-loader?

```
ERROR in ./cms/elements/CmsElementSubCategories.vue?vue&type=style&index=0&id=9122fbb2&lang=scss&scoped=true& (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./cms/elements/CmsElementSubCategories.vue?vue&type=style&index=0&id=9122fbb2&lang=scss&scoped=true&)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: 1, column 23
    at C:\Users\info\Projects\test\test-shopware-storefront\cms\elements\CmsElementSubCategories.vue:1:342
    at Parser.error (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss-values-parser\lib\parser.js:127:11)
    at Parser.operator (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss-values-parser\lib\parser.js:162:20)
    at Parser.parseTokens (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss-values-parser\lib\parser.js:245:14)
    at Parser.loop (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss-values-parser\lib\parser.js:132:12)
    at Parser.parse (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss-values-parser\lib\parser.js:51:17)
    at parse (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss-custom-properties\index.cjs.js:47:30)
    at C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss-custom-properties\index.cjs.js:333:24
    at C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss\lib\container.js:194:18
    at C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss\lib\container.js:139:18
    at Rule.each (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss\lib\container.js:105:16)
    at Rule.walk (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss\lib\container.js:135:17)
    at C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss\lib\container.js:152:24
    at Root.each (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss\lib\container.js:105:16)
    at Root.walk (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss\lib\container.js:135:17)
    at Root.walkDecls (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss\lib\container.js:192:19)
    at transformProperties (C:\Users\info\Projects\test\test-shopware-storefront\node_modules\postcss-custom-properties\index.cjs.js:330:8)
 @ ./cms/elements/CmsElementSubCategories.vue?vue&type=style&index=0&id=9122fbb2&lang=scss&scoped=true& (./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./cms/elements/CmsElementSubCategories.vue?vue&type=style&index=0&id=9122fbb2&lang=scss&scoped=true&) 4:14-428
 @ ./cms/elements/CmsElementSubCategories.vue?vue&type=style&index=0&id=9122fbb2&lang=scss&scoped=true&
 @ ./cms/elements/CmsElementSubCategories.vue
 @ ./.shopware-pwa/sw-cms/cmsNameMapper.js
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@shopware-pwa/default-theme/dist/cms/CmsGenericSection.vue?vue&type=script&lang=js&
 @ ./node_modules/@shopware-pwa/default-theme/dist/cms/CmsGenericSection.vue?vue&type=script&lang=js&
 @ ./node_modules/@shopware-pwa/default-theme/dist/cms/CmsGenericSection.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@shopware-pwa/default-theme/dist/cms/CmsPage.vue?vue&type=script&lang=js&
 @ ./node_modules/@shopware-pwa/default-theme/dist/cms/CmsPage.vue?vue&type=script&lang=js&
 @ ./node_modules/@shopware-pwa/default-theme/dist/cms/CmsPage.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./.shopware-pwa/source/components/views/frontend.navigation.page.vue?vue&type=script&lang=js&
 @ ./.shopware-pwa/source/components/views/frontend.navigation.page.vue?vue&type=script&lang=js&
 @ ./.shopware-pwa/source/components/views/frontend.navigation.page.vue
 @ ./.shopware-pwa/source/components/views lazy ^\.\/.*\.vue$ namespace object
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./.shopware-pwa/source/pages/_.vue?vue&type=script&lang=js&
 @ ./.shopware-pwa/source/pages/_.vue?vue&type=script&lang=js&
 @ ./.shopware-pwa/source/pages/_.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
 ```
