### ISSUE TITLE
postcss 8.4.6 breaks rtlcss

### ISSUE THREAD

**Issue by XhmikosR** [postcss/postcss#1716]
```
> rtlcss@3.5.0 mocha
> mocha



  ..........................................................................................
  ..........................................................................................
  ..........................................................................................
  ...............................................!!!........................................
  ..........................................

  399 passing (397ms)
  3 failing

  1) # RTLCSS (Directives):
       Should insert value. (clean:false):

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'div { font-family: "Droid Sans"/*rtl:insert:, "Droid Arabic Kufi"*/, Tahoma; }'
- 'div { font-family: "Droid Sans", "Droid Arabic Kufi"/*rtl:insert:, "Droid Arabic Kufi"*/, Tahoma; }'
      + expected - actual

      -div { font-family: "Droid Sans"/*rtl:insert:, "Droid Arabic Kufi"*/, Tahoma; }
      +div { font-family: "Droid Sans", "Droid Arabic Kufi"/*rtl:insert:, "Droid Arabic Kufi"*/, Tahoma; }

      at Context.<anonymous> (test\test.js:35:20)
      at processImmediate (node:internal/timers:464:21)

  2) # RTLCSS (Directives):
       Should insert value. (!important comment):

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'div { font-family: "Droid Sans"/*!rtl:insert:, "Droid Arabic Kufi"*/, Tahoma; }'
- 'div { font-family: "Droid Sans", "Droid Arabic Kufi", Tahoma; }'
      + expected - actual

      -div { font-family: "Droid Sans"/*!rtl:insert:, "Droid Arabic Kufi"*/, Tahoma; }
      +div { font-family: "Droid Sans", "Droid Arabic Kufi", Tahoma; }

      at Context.<anonymous> (test\test.js:35:20)
      at processImmediate (node:internal/timers:464:21)

  3) # RTLCSS (Directives):
       Should insert value. (clean:false, !important comment):

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'div { font-family: "Droid Sans"/*!rtl:insert:, "Droid Arabic Kufi"*/, Tahoma; }'
- 'div { font-family: "Droid Sans", "Droid Arabic Kufi"/*!rtl:insert:, "Droid Arabic Kufi"*/, Tahoma; }'
      + expected - actual

      -div { font-family: "Droid Sans"/*!rtl:insert:, "Droid Arabic Kufi"*/, Tahoma; }
      +div { font-family: "Droid Sans", "Droid Arabic Kufi"/*!rtl:insert:, "Droid Arabic Kufi"*/, Tahoma; }

      at Context.<anonymous> (test\test.js:35:20)
      at processImmediate (node:internal/timers:464:21)
```

Going back to v8.4.5 works again without any issues.

Refs https://github.com/MohammadYounes/rtlcss/pull/280

**Comment by XhmikosR** [comment]
Closing in favor of #1717
