### ISSUE TITLE
Bad error on double ::

### ISSUE THREAD

**Issue by ai** [postcss/postcss#172]
```css
.a {
    width:: 100;
}
```

```
TypeError: Cannot read property '0' of null
    at Parser.checkMissedSemicolon (/home/ai/Dev/amplifr/front/node_modules/gulp-postcss/node_modules/postcss/lib/parser.js:370:25)
    at Parser.decl (/home/ai/Dev/amplifr/front/node_modules/gulp-postcss/node_modules/postcss/lib/parser.js:249:18)
    at Parser.word (/home/ai/Dev/amplifr/front/node_modules/gulp-postcss/node_modules/postcss/lib/parser.js:129:30)
    at Parser.loop (/home/ai/Dev/amplifr/front/node_modules/gulp-postcss/node_modules/postcss/lib/parser.js:46:26)
    at Function.module.exports [as parse] (/home/ai/Dev/amplifr/front/node_modules/gulp-postcss/node_modules/postcss/lib/parse.js:11:12)
    at PostCSS.process (/home/ai/Dev/amplifr/front/node_modules/gulp-postcss/node_modules/postcss/lib/postcss.js:43:30)
```

**Comment by ai** [comment]
Done 92d6fbc
