### ISSUE TITLE
a syntaxError without enough context info: postcss SyntaxError: Unexpected token (72:13)

### ISSUE THREAD

**Issue by scil** [postcss/postcss#1737]
first I encounter this error with webpack and postcss-loader, to focus the underlying issue, I install postcss-cli and run
`npx postcss Assets\css\app.css -o tmp.css --verbose`

error:
```

Processing Assets\css\app.css...

SyntaxError: Unexpected token (72:13)
    at _class.pp$4.raise (c:\my\node_modules\acorn\dist\acorn.js:2927:15)
    at _class.pp.unexpected (c:\my\node_modules\acorn\dist\acorn.js:698:10)
    at _class.pp.expect (c:\my\node_modules\acorn\dist\acorn.js:692:28)
    at _class.pp$3.parseObj (c:\my\node_modules\acorn\dist\acorn.js:2563:14)
    at _class.pp$3.parseExprAtom (c:\my\node_modules\acorn\dist\acorn.js:2302:19)
    at _class.parseExprAtom (c:\my\node_modules\acorn-node\lib\dynamic-import\index.js:77:117)
    at _class.pp$3.parseExprSubscripts (c:\my\node_modules\acorn\dist\acorn.js:2129:21)
    at _class.pp$3.parseMaybeUnary (c:\my\node_modules\acorn\dist\acorn.js:2106:19)
    at _class.parseMaybeUnary (c:\my\node_modules\acorn-node\lib\private-class-elements\index.js:122:54)
    at _class.pp$3.parseExprOps (c:\my\node_modules\acorn\dist\acorn.js:2041:21) {
  pos: 1864,
  loc: Position { line: 72, column: 13 },
  raisedAt: 1865
}
```

in the error msg, there is just position( line and column ) , no filename.

At last, I found the file is `tailwind.config.js` which I missed `:` in an object.

Is there any way to display the file name which cause the error?

**Comment by ai** [comment]
This is not PostCSS error object.

Looks like it is combing from `acorn`.

**Comment by ai** [comment]
Maybe some plugin use `acorn`?

**Comment by scil** [comment]
> Maybe some plugin use `acorn`?

Today I encounter the same error, and hard to find the cause.

Somebody  said: `After wasting a couple of days, I found that there was a simple typo in my tailwind.config.js` https://stackoverflow.com/questions/65592807/tailwind-css-build-error-acorn-unexpected-token-2633

quote this same situation: https://github.com/acornjs/acorn/issues/260#issuecomment-102949469
> It looks like dependency-check is just running against a folder but not reporting filename where error occurs - so better to raise issue on their repo so that they could add better reporting.

So I think postcss should report which filename.  

Or is there any helpful option for postcss to debug or print infomation?

**Comment by ai** [comment]
> So I think postcss should report which filename.

PostCSS adds filename to error message when the runner gives file name to PostCSS by `from` option.

This message is not even from PostCSS. I can’t fix it.
