### ISSUE TITLE
nix tauri integration fails

### ISSUE THREAD

**Issue by thinkrapido** [postcss/postcss#1805]
### Describe the bug

I think, the problem is, because the processing mechanism of postcss.

I followed the installation instructions of tailwindcss from the webpage https://tailwindcss.com/docs/guides/sveltekit

I get

```
[vite] Internal server error: [postcss] /<abs path to project>/src/routes/+page.svelte?svelte&type=style&lang.css:1:1: Unknown word
  Plugin: vite:css
  File: /<abs path to project>/src/routes/+page.svelte?svelte&type=style&lang.css:1:1
  1  |  <script>
     |   ^
  2  |    import Greet from "$lib/Greet.svelte";
  3  |  </script>

```

### Reproduction

1. Blank install of tauri with svelte & Typescript
2. Adding tailwind described on webpage https://tailwindcss.com/docs/guides/sveltekit

### Expected behavior

We are having here an absolute path from the filesystem.
I suppose, postcss needs an url to attach url parameters on it to parse the css

?svelte&type=style&lang.css:1:1

### Platform and versions

I think any

### Stack trace

```shell
at Input.error (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/input.js:148:16)
      at Parser.unknownWord (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:540:22)
      at Parser.other (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:164:12)
      at Parser.parse (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parser.js:72:16)
      at parse (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/home/jbc/Work/indi/indi-desktop/node_modules/postcss/lib/processor.js:28:14)
      at compileCSS (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:37647:14)
      at async TransformContext.transform (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:37121:56)
      at async Object.transform (file:///home/jbc/Work/indi/indi-desktop/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:42569:30)
```

**Comment by thinkrapido** [comment]
Original Post: https://github.com/tauri-apps/tauri/issues/5839

**Comment by ai** [comment]
Sorry, I can’t help with environment.

Can you show a problem in pure PostCSS API?

**Comment by thinkrapido** [comment]
This is a nix related issue.
I investigate it further and give feedback.

**Comment by thinkrapido** [comment]
Sorry, this is not a nix specific problem.
I can replicate it with ubuntu 22.04.

**Comment by thinkrapido** [comment]
rm -rf src-tauri/target
rm -rf .svelte-kit
yarn tauri dev
fixes it

!!!SOLVED!!!

**Comment by Richdark** [comment]
Hi, has anybody ever resolved this issue? I've checked the other issues at [tailwindcss](https://github.com/tailwindlabs/tailwindcss/issues/10081) and [tauri](https://github.com/tauri-apps/tauri/issues/5839) repos but none of the solutions really helped me at all. I'm pretty new to the whole JavaScript "ecosystem" (not really sure if there is some word for this) so I'm not able to track nor debug the issue. I'm using a combination of Tauri, npm, Svelte with pure JS and Melt UI, my stack trace is basically the same as yours though, so I'd guess the issues lies somewhere in between Tauri and PostCSS. What's interesting is that when I uninstall Melt UI, the issue disappears. Even having Tailwind CSS installed (without Melt UI) everything is working correctly.

**Comment by yueduz** [comment]
I have the same problem when I open it from npm run tauri dev.
I run npm run dev and open http://localhost:1420/ from chrome without any problem.

**Comment by yueduz** [comment]
> rm -rf src-tauri/target rm -rf .svelte-kit yarn tauri dev fixes it
> 
> !!!SOLVED!!!

It doesn't work for me
@thinkrapido How do you decide now?
