### ISSUE TITLE
Failed to load PostCSS config

### ISSUE THREAD

**Issue by happysalada** [postcss/postcss#1844]
here is the full stacktrace
```

> immutable-coin@0.0.1 dev /Users/raphael/dev/immutable_coin
> vite dev


/Users/raphael/dev/immutable_coin/node_modules/.pnpm/postcss@8.4.24/node_modules/postcss/lib/input.js:6
let { nanoid } = require('nanoid/non-secure')
                 ^

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /Users/raphael/dev/immutable_co
Instead change the require of index.js in /Users/raphael/dev/immutable_coin/node_modules/.pnpm/postcss@8.4
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/raphael/dev/immutable_coin/node_modules/.pnpm/nanoi
    at Object.<anonymous> (/Users/raphael/dev/immutable_coin/node_modules/.pnpm/postcss@8.4.24/node_modules/postcss/lib/input.js:6:18)
    at Object.<anonymous> (/Users/raphael/dev/immutable_coin/node_modules/.pnpm/postcss@8.4.24/node_modules/postcss/lib/map-generator.js:7:13)
    at Object.<anonymous> (/Users/raphael/dev/immutable_coin/node_modules/.pnpm/postcss@8.4.24/node_modules/postcss/lib/lazy-result.js:4:20)
    at Object.<anonymous> (/Users/raphael/dev/immutable_coin/node_modules/.pnpm/postcss@8.4.24/node_modules/postcss/lib/postcss.js:5:18)
    at Object.<anonymous> (/Users/raphael/dev/immutable_coin/node_modules/.pnpm/tailwindcss@3.3.2/node_modules/tailwindcss/lib/lib/setupContextUtils.js:30:57)
    at Object.<anonymous> (/Users/raphael/dev/immutable_coin/node_modules/.pnpm/tailwindcss@3.3.2/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:21:28)
    at Object.<anonymous> (/Users/raphael/dev/immutable_coin/node_modules/.pnpm/tailwindcss@3.3.2/node_modules/tailwindcss/lib/plugin.js:5:70)
    at Object.<anonymous> (/Users/raphael/dev/immutable_coin/node_modules/.pnpm/tailwindcss@3.3.2/node_modules/tailwindcss/lib/index.js:2:18)
    at Object.<anonymous> (/Users/raphael/dev/immutable_coin/postcss.config.cjs:1:21)
    at async importDefault (file:///Users/raphael/dev/immutable_coin/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36460:18)
    at async Object.search (file:///Users/raphael/dev/immutable_coin/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:28897:38)] {
  code: 'ERR_REQUIRE_ESM'
}
```

it looks like the issue was fixed in nanoid, but I have it re-appearing with the latest versions.
Not sure why.

my `postcsss.config.cjs` looks like
```
const tailwindcss = require("tailwindcss");
const autoprefixer = require("autoprefixer");

const config = {
  syntax: 'postcss-scss',
  plugins: [
    //Some plugins, like tailwindcss/nesting, need to run before Tailwind,
    tailwindcss(),
    //But others, like autoprefixer, need to run after,
    autoprefixer
  ]
};

module.exports = config;
```

**Comment by ai** [comment]
Check what version of `nanoid` do you have in your lock file. You should have 3.x (which is CJS), and not 4.x (which is ESM-only).

PostCSS uses `nanoid@3`, but maybe something was broken in `node_modules` https://github.com/postcss/postcss/blob/main/package.json#L82

**Comment by happysalada** [comment]
I've got both versions in my lockfile
one module I installed depends on 4.x

```
  /nanoid@3.3.6:
    resolution: {integrity: sha512-BGcqMMJuToF7i1rt+2PWSNVnWIkGCU78jBG3RxO/bZlnZPK2Cmi2QaffxGO/2RvWi9sL+FAiRiXMgsyxQ1DIDA==}
    engines: {node: ^10 || ^12 || ^13.7 || ^14 || >=15.0.1}
    hasBin: true
    dev: true

  /nanoid@4.0.2:
    resolution: {integrity: sha512-7ZtY5KTCNheRGfEFxnedV5zFiORN1+Y1N6zvPTnHQd8ENUvfaDBeuJDZb2bN/oXwXxu3qkTXDzy57W5vAmDTBw==}
    engines: {node: ^14 || ^16 || >=18}
    hasBin: true
    dev: false
```

**Comment by ai** [comment]
1. Try to delete `node_modules` and install it again
2. Try to move lock file to somewhere, and install dependencies again with lock-file recreation
3. Try to check your `pnpm` version and update to latest version (maybe it is a bug)
4. Show the content of `/Users/raphael/dev/immutable_coin/node_modules/.pnpm/postcss@8.4.24` and ``/Users/raphael/dev/immutable_coin/node_modules/.pnpm/postcss@8.4.24/node_modules`

**Comment by happysalada** [comment]
ha, I had tried re-installing but hadn't deleted the node_modules.
deleting the node_modules and removing the `.pnpm` directory and re-installing fixed it.

Thanks a lot for the lightspeed help!
