### ISSUE TITLE
Unkown word Error

### ISSUE THREAD

**Issue by TryBlock** [postcss/postcss#1912]
I'am get this error message when i try to build my nextjs and payloadcms project

```
ffblankenfelde@0.1.0 build:next D:\apps\ffblankenfelde
> cross-env PAYLOAD_CONFIG_PATH=dist/payload.config.js NEXT_BUILD=true node dist/server.js

[12:43:10] INFO (payload): Starting Payload...
[12:43:13] INFO (payload): Admin URL http://localhost:3000/admin
[12:43:13] INFO (payload): Next.js is building for production
   ▲ Next.js 14.0.4
   - Environments: .env

 ⚠ Failed to minify the stylesheet for function() {
      return this[~~(Math.random() * this.length)];
    }. Skipped optimizing this font.
CssSyntaxError: <css input>:2:7: Unknown word
    at Input.error (D:\apps\ffblankenfelde\node_modules\.pnpm\postcss@8.4.31\node_modules\postcss\lib\input.js:106:16)
    at Parser.unknownWord (D:\apps\ffblankenfelde\node_modules\.pnpm\postcss@8.4.31\node_modules\postcss\lib\parser.js:594:22)
    at Parser.other (D:\apps\ffblankenfelde\node_modules\.pnpm\postcss@8.4.31\node_modules\postcss\lib\parser.js:436:12)
    at Parser.parse (D:\apps\ffblankenfelde\node_modules\.pnpm\postcss@8.4.31\node_modules\postcss\lib\parser.js:471:16)
    at parse (D:\apps\ffblankenfelde\node_modules\.pnpm\postcss@8.4.31\node_modules\postcss\lib\parse.js:11:12)
    at new LazyResult (D:\apps\ffblankenfelde\node_modules\.pnpm\postcss@8.4.31\node_modules\postcss\lib\lazy-result.js:133:16)
    at Processor.process (D:\apps\ffblankenfelde\node_modules\.pnpm\postcss@8.4.31\node_modules\postcss\lib\processor.js:53:14)
    at minifyCss (D:\apps\ffblankenfelde\node_modules\.pnpm\next@14.0.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\webpack\plugins\font-stylesheet-gathering-plugin.js:70:8)  
    at D:\apps\ffblankenfelde\node_modules\.pnpm\next@14.0.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\build\webpack\plugins\font-stylesheet-gathering-plugin.js:194:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'Unknown word',
  source: 'function() {\n      return this[~~(Math.random() * this.length)];\n    }',
  line: 2,
  column: 7,
  endLine: 2,
  endColumn: 13,
  input: {
    column: 7,
    endColumn: 13,
    endLine: 2,
    line: 2,
    source: 'function() {\n      return this[~~(Math.random() * this.length)];\n    }'
  }
}
   Creating an optimized production build  ...webpack built e0276649c744467fe483 in 55038ms
webpack compiled successfully
```
My Package.json
```json
{
  "name": "ffblankenfelde",
  "version": "0.1.0",
  "private": true,
  "main": "dist/server.js",
  "scripts": {
    "dev": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts nodemon",
    "generate:types": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload generate:types",
    "build:payload": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload build",
    "build:server": "tsc --project tsconfig.server.json",
    "build:next": "cross-env PAYLOAD_CONFIG_PATH=dist/payload.config.js NEXT_BUILD=true node dist/server.js",
    "build": "cross-env NODE_ENV=production pnpm build:payload && pnpm build:server && pnpm copyfiles && pnpm build:next",
    "start": "cross-env PAYLOAD_CONFIG_PATH=dist/payload.config.js NODE_ENV=production node dist/server.js",
    "copyfiles": "copyfiles -u 1 \"src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png}\" dist/",
    "lint": "next lint"
  },
  "dependencies": {
    "@faceless-ui/modal": "^2.0.1",
    "@hookform/resolvers": "^3.3.2",
    "@payloadcms/bundler-webpack": "^1.0.5",
    "@payloadcms/db-postgres": "^0.2.0",
    "@payloadcms/plugin-form-builder": "^1.0.15",
    "@payloadcms/plugin-nested-docs": "^1.0.9",
    "@payloadcms/plugin-seo": "^1.0.15",
    "@payloadcms/richtext-slate": "^1.2.1",
    "@radix-ui/react-accordion": "^1.1.2",
    "@radix-ui/react-checkbox": "^1.0.4",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-dropdown-menu": "^2.0.6",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-popover": "^1.0.7",
    "@radix-ui/react-scroll-area": "^1.0.5",
    "@radix-ui/react-select": "^2.0.0",
    "@radix-ui/react-separator": "^1.0.3",
    "@radix-ui/react-slot": "^1.0.2",
    "@radix-ui/react-tabs": "^1.0.4",
    "@react-email/components": "^0.0.12",
    "@t3-oss/env-core": "^0.7.1",
    "@t3-oss/env-nextjs": "^0.7.1",
    "@tailwindcss/line-clamp": "^0.4.4",
    "@tanstack/react-query": "4.36.1",
    "@trpc/client": "^10.44.1",
    "@trpc/next": "^10.44.1",
    "@trpc/react-query": "^10.44.1",
    "@trpc/server": "^10.44.1",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.0.0",
    "dotenv": "^16.3.1",
    "escape-html": "^1.0.3",
    "express": "^4.18.2",
    "lucide": "^0.294.0",
    "lucide-react": "^0.294.0",
    "next": "14.0.4",
    "nodemailer": "^6.9.7",
    "payload": "^2.3.1",
    "pdfjs-dist": "^4.0.269",
    "react": "^18",
    "react-dom": "^18",
    "react-hook-form": "^7.49.0",
    "react-pdf": "^7.6.0",
    "slate": "^0.91.4",
    "slate-react": "^0.92.0",
    "swiper": "^11.0.5",
    "tailwind-merge": "^2.1.0",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@types/escape-html": "^1.0.4",
    "@types/express": "^4.17.21",
    "@types/node": "^20",
    "@types/nodemailer": "^6.4.14",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "copyfiles": "^2.4.1",
    "eslint": "^8",
    "eslint-config-next": "14.0.3",
    "nodemon": "^3.0.2",
    "postcss": "^8.4.32",
    "tailwindcss": "^3.4.0",
    "ts-node": "^10.9.1",
    "typescript": "^5"
  }
}
```

Have anyone a idee why this error was thrown

**Comment by ai** [comment]
In you example you have JS code. Seems like it is an issue in build process, not PostCSS.

**Comment by TryBlock** [comment]
The code snippet 
```js
function() {
      return this[~~(Math.random() * this.length)];
}
```
is nowhere to be found in my code

**Comment by ai** [comment]
Very likely it was processed by your build process.

It is defiantly not CSS and can’t be parsed by PostCSS.

**Comment by TryBlock** [comment]
But where does it come from

**Comment by ai** [comment]
You need to do a proper debug, which is a work. I can’t do a work for you for free.

You can try to ask ChatGPT or your builder’s community if you try to avoid research.
