### ISSUE TITLE
Errors using Sass-style modules following example in Readme

### ISSUE THREAD

**Issue by itmustbe** [postcss/postcss#282]
I'm totally new to PostCSS.  I'm using Yeoman with the generator-gulp-webapp for scaffolding... actually I just switched to using that (from generator-webapp) because it comes with gulp-postcss, which I've been so excited to try!  Everything works fine PostCSS-wise when, for example, I use a few particular modules:

```
gulp.task('styles', function () {
  return gulp.src('app/styles/main.css')
    .pipe($.sourcemaps.init())
    .pipe($.postcss([
      require('autoprefixer-core')({browsers: ['last 1 version']}),
      require('postcss-simple-vars'),
      require('pixrem')
    ]))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream: true}));
});
```

Variables all work fine, and rem units are converted and declared first as pixels in the resulting stylesheet, all just as one would expect.

However, when I try to combine the modules you suggest for Sass emulation in your Readme here: https://github.com/postcss/postcss/#what-is-postcss I end up with lots of errors.  Let's say I try to use just postcss-nested ... when I do that, I get these errors as soon as I add a nested rule to my stylesheet:

```
[10:10:26] Starting 'styles'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: undefined is not a function
    at /Users/ef/Sites/yo/node_modules/postcss-nested/index.js:45:27
    at Rule.Container.each (/Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:94:16)
    at rule (/Users/ef/Sites/yo/node_modules/postcss-nested/index.js:41:10)
    at /Users/ef/Sites/yo/node_modules/postcss-nested/index.js:58:13
    at Root.Container.each (/Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:94:16)
    at Array.process (/Users/ef/Sites/yo/node_modules/postcss-nested/index.js:56:10)
    at PostCSS.process (/Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/postcss/lib/postcss.js:51:40)
    at DestroyableTransform.transform [as _transform] (/Users/ef/Sites/yo/node_modules/gulp-postcss/index.js:49:26)
    at DestroyableTransform.Transform._read (/Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
```

Another example: if I require and then try using postcss-mixins (and I am careful about the require order as you specify) I get this error when I try using a mixin:

```
[10:14:38] Starting 'styles'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'type' of undefined
    at Rule.Container.normalize (/Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:245:15)
    at Rule.Container.insertBefore (/Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:178:23)
    at insertMixin (/Users/ef/Sites/yo/node_modules/postcss-mixins/index.js:58:21)
    at /Users/ef/Sites/yo/node_modules/postcss-mixins/index.js:112:17
    at /Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:138:22
    at /Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:107:20
    at Rule.Container.each (/Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:94:16)
    at Rule.Container.eachInside (/Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:106:17)
    at /Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:110:24
    at Root.Container.each (/Users/ef/Sites/yo/node_modules/gulp-postcss/node_modules/postcss/lib/container.js:94:16)
```

Usually when things work for me (or not), they either do, or they don't.  In this case though some modules are definitely working, and others are definitely not, which leaves me puzzled.  Do these errors point to something that I don't understand?  I'm no Javascript developer, just someone who primarily writes a lot of CSS (currently Sass).  I'm comfortable on the command line but no programmer, in other words : )

My environment:  OS X Yosemite, Node 0.12.2, latest Yeoman, Bower, Gulp, and gulp-webapp generator, all my Node packages up-to-date (I checked again just before posting this issue!)

**Comment by ai** [comment]
Sorry, right now I am on jazz concert. I will look at your issue, when I will be at home.

**Comment by itmustbe** [comment]
I hope it's not something really obvious I'm doing wrong!  Because PostCSS feels so new there isn't as much help to be found on the web generally for specific errors, and in tutorials I've read through, it just works, just like some of the modules in your "Sass example" do for me, but not others.

I have a blog where I help people with a similar skill set to mine learn sweet new command line things with which they'd otherwise be uncomfortable.  I think folks who use Sass as a gem are finding it so slow these days, and then Node Sass is faster, but it doesn't always get the CSS right on build.  PostCSS feels super-fast, plus the modularity is so sweet (picking just what one needs for a given project!)

**Comment by ai** [comment]
I think I found problem. What `postcss` module version you use? You should use 4.0 or 4.1.

**Comment by itmustbe** [comment]
You're right!  I just realized... and there I thought everything was up-to-date too, but the latest Yeoman generator-gulp-webapp is using `postcss` 3.0 (I should have checked that in my package.json file, I really am sorry to have troubled you with this!!)

**Comment by itmustbe** [comment]
Just in case anyone else finds this issue thread helpful, I found that updating to `autoprefixer-core` 5.x.x and `gulp-postcss` 5.x.x solved the few remaining issues (errors to do with mismatched dependencies).

**Comment by ai** [comment]
I send a PR to `generator-gulp-webapp` https://github.com/yeoman/generator-gulp-webapp/pull/298
