### ISSUE TITLE
'Use process(css).then(cb) to work with async plugins'

### ISSUE THREAD

**Issue by gpleiss** [postcss/postcss#412]
We are using postcss through gulp-cssnext. Everything was working when we had postcss at verison 4.1.13. After `npm install`ing on a new machine (updating gulp-cssnext's version of postcss to 4.1.15) we're getting the following error when running our gulp task:

"Use process(css).then(cb) to work with async plugins"

Thanks!
cc/ @mattr @ctaymor

**Comment by ai** [comment]
Show please full error stacktrace to see the source of error

**Comment by isairz** [comment]
css-loader in webpack occurs same error

```
    ERROR in ./~/css-loader!./~/cssnext-loader!./assets/stylesheets/index.css
    Use process(css).then(cb) to work with async plugins

    ERROR in ./~/css-loader!./~/cssnext-loader!./assets/stylesheets/index.css
    Module build failed: ReferenceError: log is not defined
        at new Input (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/input.js:29:5)
        at Object.parse [as default] (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/parse.js:17:17)
        at new LazyResult (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:54:42)
        at Processor.process (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/processor.js:30:16)
        at processCss (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/lib/processCss.js:168:24)
        at Object.module.exports (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/lib/loader.js:21:15)
```

**Comment by ai** [comment]
Ouh, today is not my day :(

**Comment by gpleiss** [comment]
The error doesn't seem to have a stack trace. (Or maybe I'm just javascripting wrong, I don't know :grin:)

In this catch statement:

```js
      catch(err) {
        console.error('Error:', err);
        console.error('Stack:', err.stack);
      }
```

We see:

```
Error: Use process(css).then(cb) to work with async plugins
Stack: undefined
```

**Comment by ai** [comment]
@isairz what is a `Module build failed: ReferenceError: log is not defined` error? :-/ I can’t find any `log` in input

**Comment by ai** [comment]
@gpleiss sorry, I will use you as debug tool (I try to reproduce it on my projects with PostCSS, but they are fine).

Can you debug into PostCSS’s `lazy-result.js`. There are two places with `throw 'Use process(css).then(cb) to work with async plugins'`, can you find what places is used? Maybe just by `console.log` in their `if` statement?

**Comment by ai** [comment]
@gpleiss if it is `if (isPromise(promise)) {` can you show what is in `promise` and `plugin` above?

**Comment by isairz** [comment]
@ai Sorry 'log' is my mistake

```
    ERROR in ./~/css-loader!./~/cssnext-loader!./assets/stylesheets/index.css
    Use process(css).then(cb) to work with async plugins

    ERROR in ./~/css-loader!./~/cssnext-loader!./assets/stylesheets/index.css
    Module build failed: TypeError: Cannot read property 'toString' of undefined
        at new Input (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/input.js:10:23)
        at Object.parse [as default] (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/parse.js:5:17)
        at new LazyResult (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:28:24)
        at Processor.process (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/processor.js:14:16)
        at processCss (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/lib/processCss.js:168:24)
        at Object.module.exports (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/lib/loader.js:21:15)
```

**Comment by ai** [comment]
@isairz do you use postcss-loader also?

**Comment by gpleiss** [comment]
It's in `if (isPromise(promise))`.

```js
Promise: {}
Plugin: function (styles, result) {
    const opts = assign({}, options || {})
    // auto add from option if possible
    if (
      !opts.from &&
      styles &&
      styles.nodes &&
      styles.nodes[0] &&
      styles.nodes[0].source &&
      styles.nodes[0].source.input &&
      styles.nodes[0].source.input.file
    ) {
      opts.from = styles.nodes[0].source.input.file
    }

    // if from available, prepend from directory in the path array
    addInputToPath(opts)

    // if we got nothing for the path, just use cwd
    if (opts.path.length === 0) {
      opts.path.push(process.cwd())
    }

    var importedFiles = {}
    if (opts.from) {
      importedFiles[opts.from] = {
        "": true,
      }
    }
    var ignoredAtRules = []

    var hashFiles = {}

    return parseStyles(
      result,
      styles,
      opts,
      importedFiles,
      ignoredAtRules,
      null,
      hashFiles,
      createProcessor(result, options.plugins)
    ).then(function() {
      addIgnoredAtRulesOnTop(styles, ignoredAtRules)

      if (typeof opts.onImport === "function") {
        opts.onImport(Object.keys(importedFiles))
      }
    })
  }
```

**Comment by isairz** [comment]
@ai 
```
 test: /\.css$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader!cssnext-loader') }
```
I have not used postcss-loader but there are no errors at previous version.

**Comment by ai** [comment]
@isairz postcss-loader explain two errors :)

**Comment by ai** [comment]
@gpleiss can you add

```js
throw new Error('debug')
```

on one line above

```js
throw 'Use process(css).then(cb) to work with async plugins';
```

I think we have o stacktrace because I used string error.

**Comment by gpleiss** [comment]
@ai

```
Error: debug
    at LazyResult.sync (/Users/pivotal/workspace/pivotal-ui/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/lazy-result.js:185:23)
    at LazyResult.stringify (/Users/pivotal/workspace/pivotal-ui/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/lazy-result.js:215:14)
    at LazyResult.get (/Users/pivotal/workspace/pivotal-ui/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/lazy-result.js:237:25)
    at cssnext (/Users/pivotal/workspace/pivotal-ui/node_modules/gulp-cssnext/node_modules/cssnext/dist/index.js:150:20)
    at DestroyableTransform._transform (/Users/pivotal/workspace/pivotal-ui/node_modules/gulp-cssnext/index.js:26:23)
    at DestroyableTransform.Transform._read (/Users/pivotal/workspace/pivotal-ui/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/pivotal/workspace/pivotal-ui/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/pivotal/workspace/pivotal-ui/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/pivotal/workspace/pivotal-ui/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/pivotal/workspace/pivotal-ui/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:107:17)
    at queueData (/Users/pivotal/workspace/pivotal-ui/node_modules/gulp-sass/node_modules/map-stream/index.js:43:21)
    at next (/Users/pivotal/workspace/pivotal-ui/node_modules/gulp-sass/node_modules/map-stream/index.js:71:7)
    at /Users/pivotal/workspace/pivotal-ui/node_modules/gulp-sass/node_modules/map-stream/index.js:85:7
    at handleOutput (/Users/pivotal/workspace/pivotal-ui/node_modules/gulp-sass/index.js:103:3)
    at opts.success (/Users/pivotal/workspace/pivotal-ui/node_modules/gulp-sass/index.js:63:7)
    at options.success (/Users/pivotal/workspace/pivotal-ui/node_modules/node-sass/lib/index.js:163:7)
```

**Comment by ai** [comment]
@gpleiss awesome, we are close

**Comment by ai** [comment]
@isairz can you update to 4.1.16 and post your error message here?

**Comment by ai** [comment]
@gpleiss seems like your bug came from `postcss-import` update, not from PostCSS

Problem is that `gulp-cssnext` doesn’t use async API (as error says). I create a issue for your, you can write something there or just subscribe to it: https://github.com/cssnext/gulp-cssnext/issues/8

/cc @MoOx

**Comment by isairz** [comment]
@ai It occurs same error at 4.1.16.
I checked the version at ./node_modules/css-loader/node_modules/postcss/package.json

```
ERROR in ./~/css-loader!./~/cssnext-loader!./assets/stylesheets/index.css
Use process(css).then(cb) to work with async plugins

ERROR in ./~/css-loader!./~/cssnext-loader!./assets/stylesheets/index.css
Module build failed: TypeError: Cannot read property 'toString' of undefined
    at new Input (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/input.js:29:23)
    at Object.parse [as default] (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/parse.js:17:17)
    at new LazyResult (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:54:42)
    at Processor.process (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/node_modules/postcss/lib/processor.js:30:16)
    at processCss (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/lib/processCss.js:168:24)
    at Object.module.exports (/Users/isair/go/src/github.com/isairz/brave/yomiko/node_modules/css-loader/lib/loader.js:21:15)
 @ ./assets/stylesheets/index.css 4:14-124 13:2-17:4 14:20-130
```

**Comment by gpleiss** [comment]
@ai bummer that it's an issue with gulp-cssnext, but thanks so much for all your help! :smiley:

**Comment by ai** [comment]
@isairz Very strange, why `Use process(css).then(cb) to work with async plugins` error still has no backtrace to find that async plugin.

Can you disable postcss-loader?

What css-loader config do you use?

**Comment by ai** [comment]
@gpleiss we are all family with cssnext, cssnano, css modules, etc ^_^

**Comment by ai** [comment]
@isairz I create this issue for you, please report config there: https://github.com/webpack/css-loader/issues/95

**Comment by gdub22** [comment]
Hit this today too. Here's the stack trace with 4.1.16
```
Use process(css).then(cb) to work with async plugins
Error: Use process(css).then(cb) to work with async plugins
    at LazyResult.sync (/Users/garth/dev/web/bustle/node_modules/ember-cli-cssnext/node_modules/broccoli-cssnext-single/node_modules/cssnext/node_modules/postcss/lib/lazy-result.js:185:23)
    at LazyResult.stringify (/Users/garth/dev/web/bustle/node_modules/ember-cli-cssnext/node_modules/broccoli-cssnext-single/node_modules/cssnext/node_modules/postcss/lib/lazy-result.js:214:14)
    at LazyResult.get (/Users/garth/dev/web/bustle/node_modules/ember-cli-cssnext/node_modules/broccoli-cssnext-single/node_modules/cssnext/node_modules/postcss/lib/lazy-result.js:241:25)
    at CssnextCompiler.updateCache (/Users/garth/dev/web/bustle/node_modules/ember-cli-cssnext/node_modules/broccoli-cssnext-single/index.js:49:13)
    at /Users/garth/dev/web/bustle/node_modules/ember-cli-cssnext/node_modules/broccoli-cssnext-single/node_modules/broccoli-caching-writer/index.js:96:34
    at lib$rsvp$$internal$$tryCatch (/Users/garth/dev/web/bustle/node_modules/ember-cli-cssnext/node_modules/broccoli-cssnext-single/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/garth/dev/web/bustle/node_modules/ember-cli-cssnext/node_modules/broccoli-cssnext-single/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/garth/dev/web/bustle/node_modules/ember-cli-cssnext/node_modules/broccoli-cssnext-single/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/garth/dev/web/bustle/node_modules/ember-cli-cssnext/node_modules/broccoli-cssnext-single/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by isairz** [comment]
@ai thanks.

**Comment by MoOx** [comment]
I guess it's my bad guys. I should not have updated postcss-import this way as a minor change. It seems it's all my fault. Meanwhile you should be able to:

- uninstall postcss-import or the pack that use it (eg: cssnext or gulp-cssnext)
- npm i -S postcss-import@6.0.0  (or -D)
- reinstall your runner, the fixed (6.0.0) version or postcss-import should be used

**Comment by MoOx** [comment]
FYI, I unpublished 6.1.0 in order to prevent this issue for too many people. I will release this async version of postcss-import as 7.0.0

**Comment by MoOx** [comment]
I found a way to revert this, published as 6.1.1.

**Comment by IbthajSami** [comment]
Facing Error while removing stylesheet and tailwind css

**Comment by wanderhungerbuhler** [comment]
The same case now. Using Expo, TailwindCSS and NativeWindCSS...

**Comment by Dgzinhotrem** [comment]
managed to solve the problem

**Comment by wanderhungerbuhler** [comment]
Yes, I needed to force the packages version to:

"postcss": "8.4.23",
"tailwindcss": "3.3.2",

see if your yarn.lock is also with version 3.3.2 this influence, I say with complete certainty because I've been testing almost 24 hours a day the possibilities of this RIDICULOUS error.

But like a good BR[🇧🇷](https://emojipedia.org/pt/bandeira-brasil/), I never give up!

**Comment by ngnathan** [comment]
Same haha.  Took me forever but finally arrived at the same conclusion.  Thanks @wanderhungerbuhler

**Comment by malek0x1** [comment]
run this guys

```
yarn remove nativewind
yarn remove tailwindcss
yarn add postcss@8.4.23
yarn add --dev tailwindcss@3.3.2
yarn add nativewind
```

if using npm use npm instead of npm <3

**Comment by YhomiAce** [comment]
> run this guys
> 
> ```
> yarn remove nativewind
> yarn remove tailwindcss
> yarn add postcss@8.4.23
> yarn add --dev tailwindcss@3.3.2
> yarn add nativewind
> ```
> 
> if using npm use npm instead of yarn <3

This fixed it for me. Thanks @malek0x1

**Comment by Kylar13** [comment]
Hello!

This issue is happening to me as well on an Expo + Nativewind setup, but only seems to happen when building for Android, for iOS build everything works fine.

I downgraded to tailwind 3.3.2 and clean installed all dependencies but I'm still getting the same error

![image](https://github.com/postcss/postcss/assets/7138244/7296458c-40a3-450b-bb14-c810abfa0b7f)

Any idea about other things I could try? How can I force pnpm to install a compatible version of postcss? Shouldn't it already be doing that when I downgraded to tailwindcss@3.3.2 ?

**Comment by ngnathan** [comment]
> Hello!
> 
> This issue is happening to me as well on an Expo + Nativewind setup, but only seems to happen when building for Android, for iOS build everything works fine.
> 
> I downgraded to tailwind 3.3.2 and clean installed all dependencies but I'm still getting the same error
> 
> ![image](https://user-images.githubusercontent.com/7138244/254548775-7296458c-40a3-450b-bb14-c810abfa0b7f.png)
> 
> Any idea about other things I could try? How can I force pnpm to install a compatible version of postcss? Shouldn't it already be doing that when I downgraded to tailwindcss@3.3.2 ?

Maybe double check dependencies to see if it actually installed `tailwindcss@3.3.2`.  Run `pnpm why tailwindcss`.  Make sure `package.json` doesn't have something like `^3.3.2` and that it's just `3.3.2`.

Also check to make sure you're running `postcss@8.4.23`.

**Comment by Kylar13** [comment]
> Maybe double check dependencies to see if it actually installed `tailwindcss@3.3.2`. Run `pnpm why tailwindcss`. Make sure `package.json` doesn't have something like `^3.3.2` and that it's just `3.3.2`.
> 
> Also check to make sure you're running `postcss@8.4.23`.

They're both set at `postcss@8.4.23` and `tailwindcss@3.3.2`, but checking the lockfiles pnpm is still installing `postcss@8.4.24` for `tailwindcss@3.3.2`, as you can see here:

![image](https://github.com/postcss/postcss/assets/7138244/82db7044-39cd-428f-87ff-f3190641f1ba)

I'll try again clearing the lockfiles and node_modules

**Comment by usama-mk** [comment]
Just downgrade the version to 3.3.2:

- `yarn add --dev tailwindcss@3.3.2`

Assuming you've installed nativewind (yard add nativewind)

**This worked for me!**
