### ISSUE TITLE
-webkit-mask-box-image should be parsed properly

### ISSUE THREAD

**Issue by j6lim** [postcss/postcss#575]
I am using postcss 5.0.6 with webpack 1.12.2 and css-loader 0.18.0

My css (I am using Framework7 1.2.0) contains this style

```
.message-sent .message-text {
  padding-right: 22px;
  background-color: #00d449;
  color: white;
  margin-left: auto;
  -webkit-mask-box-image: url("data:image/svg+xml;charset=utf-8,<svg height='35' viewBox='0 0 96 70' width='48' xmlns='http://www.w3.or/2000/svg'><path d='m84 35c1 7-5 37-42 35-37 2-43-28-42-35-1-7 5-37 42-35 37-2 43 28 42 35z'/></svg>") 50% 56% 46% 42%;
}
```

and postcss seems not recognizing  -webkit-mask-box-image field properly. the correct syntax is written here.

https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-mask-box-image

postcss recognizes the whole entries 'url("data:image/svg+xml;charset=utf-8,<svg height='35' viewBox='0 0 96 70' width='48' xmlns='http://www.w3.or/2000/svg'><path d='m84 35c1 7-5 37-42 35-37 2-43-28-42-35-1-7 5-37 42-35 37-2 43 28 42 35z'/></svg>") 50% 56% 46% 42%' as an image url and passes it through postcss-svgo, which invokes this error.

````
Module build failed: URIError: URI malformed
    at decodeURIComponent (native)
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-svgo/dist/index.js:27:28
    at minifyPromise (/Users/j6lim/myproject/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-svgo/dist/index.js:26:12)
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-svgo/dist/index.js:58:35
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/container.js:88:34
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/container.js:73:26
    at Rule.each (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/container.js:59:22)
    at Rule.walk (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/container.js:72:21)
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/container.js:76:32
    at Root.each (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/container.js:59:22)
    at Root.walk (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/container.js:72:21)
    at Root.walkDecls (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/container.js:86:25)
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-svgo/dist/index.js:56:17
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-svgo/dist/index.js:54:16
    at LazyResult.run (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:201:20)
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:115:37
    at LazyResult.asyncTick (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at processing.Promise.then._this2.processed (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:155:20)
    at LazyResult.async (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:27)
    at LazyResult.then (/Users/j6lim/myproject/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
    at processCss (/Users/j6lim/myproject/node_modules/css-loader/lib/processCss.js:195:5)
    at Object.module.exports (/Users/j6lim/myproject/node_modules/css-loader/lib/loader.js:22:2)
 @ ./~/framework7/dist/css/framework7.ios.min.css 4:14-82
````

**Comment by TrySound** [comment]
@j6lim It's postcss-svg issue. Place it [here](https://github.com/ben-eb/postcss-svgo/issues)
