### ISSUE TITLE
"SyntaxError: Unexpected reserved word" in 5.0.7

### ISSUE THREAD

**Issue by Tenzer** [postcss/postcss#582]
When I try to use postcss 5.0.7 via cssnano, I now get the following exception on both Node 4.1.1 and 0.12.7, which I don't get with 5.0.6:

    /path/to/project/node_modules/postcss/lib/postcss.es6:1
    (function (exports, require, module, __filename, __dirname) { import Declaration from './declaration';
                                                                  ^^^^^^

    SyntaxError: Unexpected reserved word
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:413:25)
        at Module._extensions..js (module.js:452:10)
        at Object.require.extensions.(anonymous function) [as .es6] (/path/to/project/node_modules/babel-core/lib/api/register/node.js:214:7)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/path/to/project/node_modules/postcss/index.js:2:18)
        at Module._compile (module.js:434:26)

Looking through the [changes made between version 5.0.6 and 5.0.7](https://github.com/postcss/postcss/compare/5.0.6...v5.0.7), I cannot figure out what should cause this problem. Hopefully you guys can.

**Comment by ahmedelgabri** [comment]
Same here...

**Comment by ben-eb** [comment]
This is resolved in 5.0.8. I missed a step when publishing the last version, sorry for the inconvenience.

**Comment by Tenzer** [comment]
Thanks!

**Comment by ahmedelgabri** [comment]
Thanks @ben-eb
