### ISSUE TITLE
Strange error at the css file loading.

### ISSUE THREAD

**Issue by franckmaurin** [postcss/postcss#600]
Hello,

I've a strange error when I compile with webpack my react project (using cssnext-loader):
```
ERROR in ./~/css-loader!./~/cssnext-loader!./src/components/Work/Single/Nav/styles.css
TypeError: Cannot read property 'map' of undefined

ERROR in ./~/css-loader!./~/cssnext-loader!./src/components/Work/Single/Nav/styles.css
Module build failed: TypeError: Cannot read property 'toString' of undefined
    at new Input (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/input.js:31:23)
    at parse (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/parse.js:21:17)
    at new LazyResult (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:57:24)
    at Processor.process (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/processor.js:36:16)
    at processCss (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/lib/processCss.js:165:11)
    at Object.module.exports (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/lib/loader.js:22:2)
 @ ./src/components/Work/Single/Nav/styles.css 4:14-143

ERROR in ./src/components/Work/Single/Nav/styles.css
Module build failed: ModuleError: TypeError: Cannot read property 'map' of undefined
    at DependenciesBlock.<anonymous> (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:79:21)
    at Object.cssnextLoader (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/cssnext-loader/index.js:36:10)
```

If I console.log the content in the /css-loader/lib/loader.js, I get "undefined" for one css file (Work/Single/Nav/styles.css).

The css file in question has this following code :
```
.workSingle-nav {
  border-top: solid 3px #fff;
  padding: 20px 0;
}
.workSingle-nav-item {
  display: inline-block;
  margin-right: 20px;
}
.workSingle-nav-item a {
  display: inline-block;
  text-decoration: none;
  font-size: 13px;
  text-transform: uppercase;
  letter-spacing: 1px;
  font-weight: 600;
  color: #fff;
}
```
The most surprising is that if I remove the line 10 "display: inline-block" , the bug disappear.

Have u any idea of this ? Thanks.

**Comment by TrySound** [comment]
@franckmaurin Show code of your loader

**Comment by franckmaurin** [comment]
@TrySound what file do you mean ?

The css file which make error is loaded like this :

```
import React    from 'react';
import { Link } from 'react-router';
import _        from 'underscore';
import styles   from './styles.css';

class WorkNav extends React.Component {
  render() {
    let prev, next;
    let back          = <li className="workSingle-nav-item workSingle-nav-item--back">
                          <Link to="/work/">Back</Link>
                        </li>;
    let brosLength    = this.props.bros.length;
    let currentIndex  = (brosLength) ? _.indexOf(this.props.bros, this.props.path): -1;
    if(brosLength && currentIndex>0) {
      prev            = <li className="workSingle-nav-item workSingle-nav-item--prev">
                          <Link to={this.props.bros[currentIndex-1]}>Previous</Link>
                        </li>;
    }
    if(currentIndex+1 < brosLength) {
      next            = <li className="workSingle-nav-item workSingle-nav-item--next">
                          <Link to={this.props.bros[currentIndex+1]}>Next</Link>
                        </li>;
    }

    return (
      <ul className="workSingle-nav">
        {prev}
        {next}
        {back}
      </ul>
    )
  }
}

export default WorkNav;
```

**Comment by TrySound** [comment]
I mean webpack config

**Comment by franckmaurin** [comment]
oh sorry.

```
var path                      = require("path");
var webpack                   = require("webpack");
var ExtractTextPlugin         = require("extract-text-webpack-plugin");

var production = process.argv.indexOf("--production") > -1;

module.exports = {

  entry: {
    index: [
      "./src/index.js",
    ]
    //, critical: "./src/critical.js"
  },

  output: {
    path: path.join(__dirname, "dist"),
    filename: "scripts.js",
    publicPath: "/",
    libraryTarget: 'umd'
  },

  resolve: {
    extensions: [
      "",
      ".js",
      ".json",
    ],
  },

  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loaders: [
          "babel"
        ]
      },
      {
        test: /\.json$/,
        loaders: [
          "json",
        ],
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract(
          "style",
          "css!cssnext"
        )
      },
      {
        test: /\.(ico|jpe?g|png|gif)$/,
        loaders: [
          "file?name=[path][name].[ext]&context=./src",
        ],
      },
      {
        test: /\.(woff|ttf|otf|eot\?#.+|svg#.+)$/,
        loaders: [
          "file?name=[path][name].[ext]&context=./src",
        ],
      },
      {
        test: /\.(html|txt)$/,
        loaders: [
          "file?name=[path][name].[ext]&context=./src",
        ],
      },
    ],
  },

  plugins: (
    [
      new ExtractTextPlugin("styles.css"),
      new webpack.DefinePlugin({
        __PROD__: production
      })
    ]
    .concat(
      production
      ? [
        new webpack.optimize.UglifyJsPlugin({
          compress: {
            warnings: false,
          },
        }),
      ]
      : []
    )
  ),

  cssnext: {
    sourcemap: !production,
    compress: production,
    browsers: "last 2 versions",
    features: {
      customProperties: {
        variables: {
          'fontUppercase': 'lft-etica, brandon-grotesque, Helvetica, Arial, sans-serif',
          'fontSerif':     'lft-etica, ff-meta-serif-web-pro, Times, "Times New Roman", serif',
          'fontSansSerif': 'lft-etica, Helvetica, Arial, sans-serif',
          'fontMonospace': 'Consolas, Menlo, Monaco, "Lucida Console", "Liberation Mono", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", "Courier New", monospace, sans-serif'
        }
      },
      customMedia: {
        extensions: {
          '--mobile': 'screen and (min-width: 1px)',
          '--tablet': 'screen and (min-width: 719px)',
          '--laptop': 'screen and (min-width: 1023px)',
          '--desktop': 'screen and (min-width: 1199px)'
        },
        appendExtensions: true
      }
    }
  }
};
```

**Comment by ai** [comment]
Very strange. Problem is that input `css` is `undefined`.

At least, we know that it is not PostCSS issue, but issue of environment.

**Comment by ai** [comment]
@franckmaurin you should open issue in cssnext-loader, `undefined` comes from there.

Also you can try to replace `cssnext-loader` to `postcss-loader` with cssnext plugin. Anyway future cssnext version will remove own tools and will use common PostCSS tools.

**Comment by MoOx** [comment]
If a "display: inline-block" added/removed change the behavior, it's likely to be a plugin issue, not a cssnext-loader issue.

**Comment by franckmaurin** [comment]
@ai Would you have you an exemple of postcss-loader usage with cssnext plugin ? I didn't find how pass my cssnext properties into the postcss array config.

**Comment by MoOx** [comment]
This should work (with postcss-cssnext)

```js
  postcss: function() {
    return [
      postcssCssnext({
        features: {
          customProperties: {
            variables: {/*...*/}
          }
        }
      })
    ]
  }
```

**Comment by franckmaurin** [comment]
@MoOx Thank you Maxime.

The same file is "undefined" according to the loader.

```
ERROR in ./~/css-loader!./~/postcss-loader!./src/components/Work/Single/Nav/styles.css
Module build failed: TypeError: Cannot read property 'map' of undefined
    at getDecls (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-merge-rules/dist/index.js:64:22)
    at partialMerge (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-merge-rules/dist/index.js:95:60)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-merge-rules/dist/index.js:184:17
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/container.js:115:34
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/container.js:73:26
    at Root.each (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/container.js:59:22)
    at Root.walk (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/container.js:72:21)
    at Root.walkRules (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/container.js:113:25)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-merge-rules/dist/index.js:190:13
    at LazyResult.run (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:201:20)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:115:37
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
 @ ./src/components/Work/Single/Nav/styles.css 4:14-143

ERROR in ./src/components/Work/Single/Nav/styles.css
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'map' of undefined
    at getDecls (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-merge-rules/dist/index.js:64:22)
    at partialMerge (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-merge-rules/dist/index.js:95:60)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-merge-rules/dist/index.js:184:17
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/container.js:115:34
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/container.js:73:26
    at Root.each (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/container.js:59:22)
    at Root.walk (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/container.js:72:21)
    at Root.walkRules (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/container.js:113:25)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-merge-rules/dist/index.js:190:13
    at LazyResult.run (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:201:20)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:115:37
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:127:27
    at LazyResult.asyncTick (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:129:15)
    at DependenciesBlock.onModuleBuildFailed (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.<anonymous> (/Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/lib/loader.js:30:18)
    at /Users/franckmaurin/Dropbox/Pro/Server/dev/franckmaurin.lh/node_modules/css-loader/lib/processCss.js:187:3
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
```

**Comment by franckmaurin** [comment]
And if I comment the same line of css, it's ok. Very strange.

**Comment by MoOx** [comment]
Now it seems it's an issue related to cssnano or a submodule poke @ben-eb

**Comment by ben-eb** [comment]
@MoOx Seems `rule.nodes` got mangled. I'll have a fix out soon. :smile:

**Comment by ben-eb** [comment]
Should be fixed by postcss-merge-rules@2.0.1, but I don't have the time to reproduce a test case locally. @franckmaurin Can you please verify?

**Comment by franckmaurin** [comment]
@ben-eb @MoOx @ai YOU ROCK GUYS! It's fixed. :D 

Thanks you, I believe in postcss. :+1:

**Comment by ben-eb** [comment]
Cool, thanks! :+1:
