### ISSUE TITLE
Node 0.10 - Error: Cannot find module 'postcss/lib/stringifier'

### ISSUE THREAD

**Issue by KingScooty** [postcss/postcss#638]
Before anyone says, upgrading node isn't really an option for the project i'm working on.

Using node 0.10.x --harmony i'm getting the following error trace when using postcss:

```shell
Error: Cannot find module 'postcss/lib/stringifier'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/mnt/hgfs/workspace/taster/node_modules/postcss-scss/lib/scss-stringifier.js:11:30)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/mnt/hgfs/workspace/taster/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/mnt/hgfs/workspace/taster/node_modules/postcss-scss/lib/scss-stringify.js:8:24)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/mnt/hgfs/workspace/taster/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/mnt/hgfs/workspace/taster/node_modules/postcss-scss/lib/scss-syntax.js:7:22)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/mnt/hgfs/workspace/taster/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/mnt/hgfs/workspace/taster/build-pipeline/sass.js:12:19)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/mnt/hgfs/workspace/taster/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at requireDir (/mnt/hgfs/workspace/taster/node_modules/require-dir/index.js:112:33)
  at Object.<anonymous> (/mnt/hgfs/workspace/taster/gulpfile.js:4:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
  at module.exports (/usr/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
  at /usr/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:99:14
  at /usr/lib/node_modules/gulp/node_modules/v8flags/index.js:38:7
  at process._tickCallback (node.js:442:13)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:929:3
```

**Comment by ai** [comment]
Seems like you have error during npm packages installation. And `postcss` package is missed.
