### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by resting** [postcss/postcss#766]
I'm getting the error below when I include the `postcss` pipe.
Not sure what's wrong.

    TypeError: Cannot read property 'on' of undefined
    at DestroyableTransform.Readable.pipe (/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:535:7)
    at Gulp.<anonymous> (/gulpfile.js:9:10)
    at module.exports (/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)

Heres the Gulpfile.js
```
var gulp = require('gulp'),
    sass = require('gulp-sass'),
    postcss = require('gulp-postcss'),
    autoprefixer = require('autoprefixer');

gulp.task('css', function () {
    return gulp.src('sass/style.scss')
        .pipe(sass().on('error', sass.logError))
        .pipe(postcss[autoprefixer({browsers: ['last 2 versions']})])
        .pipe(gulp.dest(''));
});
```

**Comment by ai** [comment]
Ask in [gulp-postcss](https://github.com/postcss/gulp-postcss) repo.

**Comment by TrySound** [comment]
@resting `on` is stream method, not sass.
```js
.pipe(sass()).on('error', sass.logError)
```

**Comment by w0rm** [comment]
@TrySound `sass()` is a transform stream, so it should extend EventEmitter

**Comment by ben-eb** [comment]
Your original code is missing a few parentheses.

```js
var gulp = require('gulp'),
    sass = require('gulp-sass'),
    postcss = require('gulp-postcss'),
    autoprefixer = require('autoprefixer');

gulp.task('css', function () {
    return gulp.src('sass/style.scss')
        .pipe(sass()).on('error', sass.logError)
        .pipe(postcss([
            autoprefixer({browsers: ['last 2 versions']})
        ]))
        .pipe(gulp.dest(''));
});
```

Have a look into http://eslint.org/ so that you can catch these mistakes more easily. :smile:

**Comment by resting** [comment]
@ben-eb 👍you're the man!
