### ISSUE TITLE
modules not correctly resolved when using with babel and webpack

### ISSUE THREAD

**Issue by pke** [postcss/postcss#829]
## Folders

```
app
app/src
app/src/index.js
app/src/api
app/src/api/api.js
```

## index.js
`import api from "api/api` 

## webpack.config.js

```
resolve: {
    extensions: ["", ".js", ".jsx"],
    root: [
      path.join(process.cwd(), "src"),
    ],
  },
postcss: [
    autoprefixer({ browsers: ["last 2 versions"] }),
  ],
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: "postcss-loader?parser=postcss-js!babel",
        exclude: /node_modules/,
        include: src,
      },
      {
        test: /\.json$/,
        loader: "json",
      },
    ],
  },
``` 

## Output

It throws this error:

```
ERROR in ./src/index.js
Module build failed: Error: Cannot find module 'api/api'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> \app\src\index.js:15:12)
    at Module._compile (module.js:541:32)
    at Object.loaderContext.exec (\app\node_modules\webpack-core\lib\NormalModuleMixin.js:88:7)
    at Object.module.exports (\app\node_modules\postcss-loader\index.js:59:23)
```

Line 59 in `postcss-loader` reads:

```es6
if ( params.parser === 'postcss-js' ) {
  source = this.exec(source, this.resource);
}
```

From the syntax of the webpack loader entry I assumed the `source` is already transformed by `babel`? 
What is the problem here? Shouldn't postcss-js simply parse the babel transpiled JS code for inline styles?

**Comment by ai** [comment]
Nope, we should continue discuss this issue in `postcss-loader` ;). No connections to main PostCSS repo ;).

**Comment by ai** [comment]
Also https://github.com/postcss/postcss-loader/issues/76#issuecomment-228002465

**Comment by pke** [comment]
Oh ok. Just after some more digging into the source code I figured it might not actually a loader problem
