### ISSUE TITLE
postcss 5.1 breaks postcss-import

### ISSUE THREAD

**Issue by madx** [postcss/postcss#860]
When using `postcss-import` 8.1.2 with `postcss` 5.1 I get the following error:

```
ERROR in ./src/styles.css
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'length' of undefined
    at module.exports (/home/madx/[redacted]/node_modules/postcss-import/lib/join-media.js:6:40)
    at /home/madx/[redacted]/node_modules/postcss-import/index.js:167:18
    at Array.map (native)
    at parseStyles (/home/madx/[redacted]/node_modules/postcss-import/index.js:166:33)
    at /home/madx/[redacted]/node_modules/postcss-import/index.js:48:12
    at LazyResult.run (/home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:286:20)
    at /home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:200:37
    at LazyResult.asyncTick (/home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:214:15)
    at processing.Promise.then._this2.processed (/home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:240:20)
    at LazyResult.async (/home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:237:27)
    at LazyResult.then (/home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:141:21)
    at Object.module.exports (/home/madx/[redacted]/node_modules/postcss-loader/index.js:63:10)
    at DependenciesBlock.onModuleBuildFailed (/home/madx/[redacted]/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/home/madx/[redacted]/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /home/madx/[redacted]/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/madx/[redacted]/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/madx/[redacted]/node_modules/postcss-loader/index.js:74:17
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./src/index.js 27:0-23
```
Everything was working fine with postcss 5.0.21 so I think there was some breaking change with 5.1 (thus not respecting semver).

Thanks for helping out :)

**Comment by ai** [comment]
Sorry, I will have free time for debug only in Friday.

**Comment by madx** [comment]
No problem, I forced 5.0.21 meanwhile :)

**Comment by ai** [comment]
Will you have time to debug? Just put `console.log` inside `postcss-import` and compare logic in 5.1 and 5.0.21.

**Comment by madx** [comment]
I tried that but I'm not really confortable with postcss source code and found nothing interesting :confused:

**Comment by akella** [comment]
postcss-partials-import throws no errors, but just dont replace @imports
Here is working and not working configurations 
![package json e2 80 94 postcss 2016-08-22 10-36-24](https://cloud.githubusercontent.com/assets/76031/17851913/217b4970-686d-11e6-9c6a-26b9c68f8dc8.jpg)

**Comment by ai** [comment]
@akella by some reason `postcss-partials-import` 2.0 imports only files started with `_` https://github.com/jonathantneal/postcss-partial-import/blob/master/lib/getPath.js#L12
