### ISSUE TITLE
The 'composes' keyword

### ISSUE THREAD

**Issue by AlesMenzel** [postcss/postcss#975]
Hi, I am having trouble setting up webpack@2.2.1 with postcss and CSS Modules. **It works great when I disable postcss**, otherwise I am getting this ugly error:

```
ERROR in ./A.scss
Module build failed: Error

... some stack trace

ERROR in ... \node_modules\extract-text-webpack-plugin\loader.js??ref--2-0! .... \node_modules\style-loader\index.js! ... \node_modules\css-loader\index.js??ref--2-2! ... \node_modules\postcss-loader\index.js??ref--2-3! ... \node_modules\sass-loader\lib\loader.js??ref--2-4! ... \_module.scss doesn't export content
```

webpack loader config section for CSS:
```
...
/*
 Load CSS Modules - Default CSS is considered as a module
 */
{
	test: /\.(scss|sass|css)$/,
	loader: extractSass.extract({
		fallback: 'style-loader',
		use: [
			{
				loader: 'css-loader',
				options: {
					sourceMap: true,
					modules: true,
					importLoaders: 2,
					// naming of module classes
					localIdentName: (() => {
						if (isProduction) {
							return '[hash:base64:5]';
						}

						return '[path][name]__[local]';
					})(),
					minimize: isProduction
				}
			},
			{
				loader: 'postcss-loader',
				options: {
					plugins: function () {
						return [
							require('autoprefixer')
						];
					}
				}
			},
			{
				loader: 'sass-loader',
				options: {
					sourceMap: true
				}
			}
		]
	})
},
...
```

I have just a simple react component that I render.
```
import React from 'react';

import styles from './A.scss';

const App = () => (
	<div className={styles.A}>
		<h2>Hello, </h2>
	</div>
);

export default App;

```

A.scss
```
.A {
	composes: B from './B.scss';

	background-color: red;
}
```

B.scss
```
.B {
	color: blue;
}
```

---

Without PostCSS I get the desired output (bundle.css):
```
.B__B {
  color: blue; }
.A__A {
  background-color: red; }
```
which exports correctly in JS as:
```
import styles from 'A.scss';  // -> outputs {"A":"A__A B__B"}
```
but I would like to use autoprefixer too.

**Dependencies:**

- node: 7.5.0
- webpack: 2.2.1
- sass-loader: 6.0.0
- style-loader: 0.13.1
- css-loader: 0.26.1
- postcss-loader: 1.3.0
- autoprefixer: 6.7.3

**Comment by ai** [comment]
Hi. I need full stacktrace and full error description.

**Comment by AlesMenzel** [comment]
This is the full log:
```
> webpack

Version: webpack 2.2.1
Time: 1752ms
[./_app.js] ./_app.js 567 bytes {0} [built]
[./_test.js] ./_test.js 667 bytes {0} [built]
[./node_modules/html-entities/index.js] ./~/html-entities/index.js 231 bytes {0} [built]
[./node_modules/react-dom/index.js] ./~/react-dom/index.js 59 bytes {0} [built]
[./node_modules/react-dom/lib/ReactDOM.js] ./~/react-dom/lib/ReactDOM.js 5.14 kB {0} [built]
[./node_modules/react-hot-loader/index.js] ./~/react-hot-loader/index.js 41 bytes {0} [built]
[./node_modules/react-hot-loader/lib/patch.js] ./~/react-hot-loader/lib/patch.js 209 bytes {0} [built]
[./node_modules/react-hot-loader/patch.js] ./~/react-hot-loader/patch.js 41 bytes {0} [built]
[./node_modules/react/react.js] ./~/react/react.js 56 bytes {0} [built]
[./node_modules/strip-ansi/index.js] ./~/strip-ansi/index.js 161 bytes {0} [built]
[./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 1.82 kB {0} [built]
   [0] multi react-hot-loader/patch webpack-hot-middleware/client ./_test.js 52 bytes {0} [built]
[./node_modules/webpack-hot-middleware/client.js] (webpack)-hot-middleware/client.js 6.68 kB {0} [built]
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 3.88 kB {0} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
    + 343 hidden modules

ERROR in ./A.scss
Module build failed: Error
    at C:\Projects\space-falcon\node_modules\webpack\lib\NormalModule.js:141:35
    at C:\Projects\space-falcon\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Projects\space-falcon\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Projects\space-falcon\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Projects\space-falcon\node_modules\postcss-loader\index.js:153:13
 @ ./_app.js 3:0-30
 @ ./_test.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./_test.js

ERROR in ./A.scss
Module build failed: Error
    at C:\Projects\space-falcon\node_modules\webpack\lib\NormalModule.js:141:35
    at C:\Projects\space-falcon\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Projects\space-falcon\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (C:\Projects\space-falcon\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Projects\space-falcon\node_modules\postcss-loader\index.js:153:13

ERROR in C:\Projects\space-falcon\node_modules\extract-text-webpack-plugin\loader.js??ref--2-0!C:\Projects\space-falcon\node_modules\style-loader\index.js!C:\Projects\space-falcon\node_modules\css-loader\index.js??ref--2-2!C:\Projects\space-falcon\node_modules\postcss-loader\index.js??ref--2-3!C:\Projects\space-falcon\node_modules\sass-loader\lib\loader.js??ref--2-4!C:\Projects\space-falcon\A.scss doesn't export content
```

**Comment by ai** [comment]
This problem is with extract-text-plugin, not PostCSS core.

Maybe @michael-ciniawsky know a solution?

But anyway you should write to webpack team.

**Comment by AlesMenzel** [comment]
I just came across https://github.com/michael-ciniawsky/postcss-loader/tree/docs and there is this little note `If you are using functions and require() inside options, you need to specify an identifier { ident: 'postcss' } for the setup to work` which seems to fix the issue.

Simply by adding the **indent options**:
```
{
	loader: 'postcss-loader',
	options: {
		ident: 'postcss',
		plugins: function () {
			return [
				require('autoprefixer')
			];
		}
	}
},
```

Thank you very much!

**Comment by michael-ciniawsky** [comment]
@AlesMenzel :D Well `{ ident: 'postcss' }` is already outdated since `webpack >= v2.2.1` which removed the necessity to add it, what version of  `extract-text-webpack-plugin` do you use `v2.0.0-rc.3`?

**Comment by AlesMenzel** [comment]
Iam using the "extract-text-webpack-plugin": "^2.0.0-rc.3" version

**Comment by michael-ciniawsky** [comment]
Then it should work without the `ident` could you `rm -rf node_modules` and make a fresh install + changes these lines 

```diff
- loader: extractSass.extract({
+ use: extractSass.extract({

{
  loader: 'postcss-loader',
  options: {
-  ident: 'postcss',
    plugins: ()  => [ require('autoprefixer')() ],
+  sourceMap: true
  }
}
``` 

if it doesn't work  please open an issue @webpack-contrib/extract-text-webpack-plugin so we can continue there, bc it's likely to be a bug then :)

**Comment by AlesMenzel** [comment]
@michael-ciniawsky Both `use` and `loader` keywords work, but removing the ident breaks the build, returning error:

```
ERROR in ./~/css-loader?{"sourceMap":true,"modules":true,"importLoaders":1,"localIdentName":"[path][name]__[local]","minimize":false}!./~/postcss-loader?{"sourceMap":true}!./src/app/containers/page/page.scss
Module build failed: Error: No PostCSS Config found in: C:\Projects\space-falcon\src\app\containers\page
    at C:\Projects\space-falcon\node_modules\postcss-load-config\index.js:51:26
 @ ./~/css-loader?{"sourceMap":true,"modules":true,"importLoaders":1,"localIdentName":"[path][name]__[local]","minimize":false}!./~/postcss-loader?{"sourceMap":true}!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./src/app/containers/page/registration/styles.scss 3:10-282 10:80-352
 @ ./src/app/containers/page/registration/styles.scss
 @ ./src/app/containers/page/registration/index.js
 @ ./src/app/routes/index.js
 @ ./src/app/app.js
 @ ./src/app/index.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./src/app/index.js
```

**Shouldn´t there be a `plugins` query parameter in the `~/postcss-loader?{"sourceMap":true}` ?**
Might be a problem with inlining the plugins in options:

```
const autoprefixer = require('autoprefixer');

{
	loader: 'postcss-loader',
	options: {
		// ident: 'postcss',
		plugins: function () {
			return [autoprefixer];
		},
		sourceMap: true
	}
},
```

**Comment by michael-ciniawsky** [comment]
> Shouldn't there be a plugins query parameter in the ~/postcss-loader?{"sourceMap":true} ?

@AlesMenzel Yep it's excatly about that, 'complex' options including a `{Function}` and/or `require()` statements needed the webpack specific `ident: 'name'` to work correctly, but this shouldn't be necessary anymore (`v2.2.1`). When you have time could you please open an issue @webpack-contrib/extract-text-webpack-plugin`  including a small repo for reproduction :) ? 
Meanwhile just keep the `ident` if that works. Thx in advance :stuck_out_tongue:
