### ISSUE TITLE
Module build failed: BrowserslistError: Unknown browser query `op_mini all`

### ISSUE THREAD

**Issue by kolesnik** [postcss/postcss#986]
Hello Guys, I am receiving this error during webpack command for production build: "rimraf dist/* && webpack -p --bail --config ./etc/webpack.config.prod.js" 

ERROR in ./~/css-loader?importLoaders=1!./~/postcss-loader!./~/less-loader!./Client/myComponent.less
    Module build failed: BrowserslistError: Unknown browser query `op_mini all`
        at error (C:\Web\node_modules\browserslist\index.js:23:15)
        at C:\Web\node_modules\browserslist\index.js:123:13
        at Array.forEach (native)
        at browserslist (C:\Web\node_modules\browserslist\index.js:95:16)
        at isSupported (C:\Web\node_modules\caniuse-api\dist\index.js:66:37)
        at C:\Web\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:95:66
        at C:\Web\node_modules\postcss-selector-parser\dist\selectors\container.js:170:26
        at Selector.each (C:\Web\node_modules\postcss-selector-parser\dist\selectors\container.js:153:22)
        at Selector.walk (C:\Web\node_modules\postcss-selector-parser\dist\selectors\container.js:169:21)
        at C:\Web\node_modules\postcss-selector-parser\dist\selectors\container.js:173:31
        at Root.each (C:\Web\node_modules\postcss-selector-parser\dist\selectors\container.js:153:22)
        at Root.walk (C:\Web\node_modules\postcss-selector-parser\dist\selectors\container.js:169:21)
        at Processor.func (C:\Web\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:88:17)
        at Processor.process (C:\Web\node_modules\postcss-selector-parser\dist\processor.js:34:14)
        at C:\Web\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:134:12
        at Array.every (native)
        at ensureCompatibility (C:\Web\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:79:22)
        at canMerge (C:\Web\node_modules\postcss-merge-rules\dist\index.js:72:44)
        at C:\Web\node_modules\postcss-merge-rules\dist\index.js:220:24
        at C:\Web\node_modules\postcss\lib\container.es6:199:28
        at C:\Web\node_modules\postcss\lib\container.es6:110:26
        at Root.each (C:\Web\node_modules\postcss\lib\container.es6:78:22)
        at Root.walk (C:\Web\node_modules\postcss\lib\container.es6:109:21)
        at Root.walkRules (C:\Web\node_modules\postcss\lib\container.es6:197:25)
        at C:\Web\node_modules\postcss-merge-rules\dist\index.js:267:13
        at LazyResult.run (C:\Web\node_modules\postcss\lib\lazy-result.es6:321:20)
        at LazyResult.asyncTick (C:\Web\node_modules\postcss\lib\lazy-result.es6:248:32)
        at LazyResult.asyncTick (C:\Web\node_modules\postcss\lib\lazy-result.es6:260:22)
        at LazyResult.asyncTick (C:\Web\node_modules\postcss\lib\lazy-result.es6:260:22)
        at LazyResult.asyncTick (C:\Web\node_modules\postcss\lib\lazy-result.es6:260:22)

and it works fine when running web pack without "-p" key

**Comment by ai** [comment]
1. Open issue in Browserslist repo.
2. Start that new issue from webpack config.

**Comment by kolesnik** [comment]
Added it there https://github.com/ai/browserslist/issues/129
Thank you!
